### ISSUE TITLE
docker run standalone is error

### ISSUE THREAD

**Issue by gumutianqi** [nacos-group/nacos-docker#1]
OS: macOS mojave 10.14

**Docker-for-Desktop Info:**

> Docker: 18.09
> Docker-Compose: 1.23.1

---

> $ docker-compose -f standalone.yaml up

Error Console Images

![image](https://user-images.githubusercontent.com/1057589/48927381-6488c400-ef10-11e8-9bdb-e77105135799.png)

**Comment by paderlol** [comment]
Thanks,I found the cause of the problem, because the database initialization script is missing, I will fix it right away.

> OS: macOS mojave 10.14
> 
> **Docker-for-Desktop Info:**
> 
> > Docker: 18.09
> > Docker-Compose: 1.23.1
> 
> > $ docker-compose -f standalone.yaml up
> 
> Error Console Images
> 
> ![image](https://user-images.githubusercontent.com/1057589/48927381-6488c400-ef10-11e8-9bdb-e77105135799.png)
Thanks,I found the cause of the problem, because the database `schema.sql` is missing, I will fix it right away.

**Comment by gumutianqi** [comment]
@paderlol 

this directory `nacos-docker/build/nacos/conf/` still no schema.sql file.

#1 

and run console log as that:

```
2018-11-23 03:51:11,268 ERROR /home/nacos/conf/schema.sql (No such file or directory)

java.lang.Exception: /home/nacos/conf/schema.sql (No such file or directory)
```

**Comment by gumutianqi** [comment]
单机模式也需要 mysql，那 standalone.yaml 是不是应该有 mysql 的 container 才对

**Comment by paderlol** [comment]
you must be pull nacos docker project again




| |
浮夸
|
|
邮箱：huangmnlove@163.com
|

签名由 网易邮箱大师 定制

On 11/23/2018 12:47, 古木天琪 wrote:

@paderlol

this directory nacos-docker/build/nacos/conf/ still no schema.sql file.

#1

and run console log as that:

2018-11-23 03:51:11,268 ERROR /home/nacos/conf/schema.sql (No such file or directory)

java.lang.Exception: /home/nacos/conf/schema.sql (No such file or directory)

**Comment by paderlol** [comment]
单机使用的是内存数据库，你重新更新下工程。或者自己把standalone.yaml里面镜像版本改成0.5.0或者latest，就可以正常使用了




| |
浮夸
|
|
邮箱：huangmnlove@163.com
|

签名由 网易邮箱大师 定制

On 11/23/2018 12:49, 古木天琪 wrote:

单机模式也需要 mysql，那 standalone.yaml 是不是应该有 mysql 的 container 才对

**Comment by gumutianqi** [comment]
OK, it's work

不过0.5.0 的image 没问题，但是latest还是有问题的版本

**Comment by paderlol** [comment]
> OK, it's work
> 
> 不过0.5.0 的image 没问题，但是latest还是有问题的版本

好的,latest我重新push了 可以正常工作了
