### ISSUE TITLE
使用docker启动的nacos-server创建不了配置文件

### ISSUE THREAD

**Issue by xingwl2018** [nacos-group/nacos-docker#100]
![image](https://user-images.githubusercontent.com/38937448/83134414-e9145e00-a116-11ea-807a-20c2c9c689c5.png)

Uncaught TypeError: Cannot read property 'currentLanguageCode' of undefined

**Comment by xingwl2018** [comment]
直接复制粘贴进去的内容进行发布时候，会报异常；但是通过手动输入不会报

**Comment by paderlol** [comment]
已解决
