### ISSUE TITLE
Nacos集群不能正常启动

### ISSUE THREAD

**Issue by leo18945** [nacos-group/nacos-docker#104]
我在mac下启动nacos集群，按照以下命令，仓库克隆下来不做任何修改
```
git clone --depth 1 https://github.com/nacos-group/nacos-docker.git && cd nacos-docker

docker-compose -f example/cluster-hostname.yaml up -d
```

结果，nacos.log日志里重复出现这个，服务起不来，一直在不停重启
```
2020-06-17 14:06:31,226 INFO The server IP list of Nacos is [nacos1:8848, nacos2:8848, nacos3:8848]

2020-06-17 14:06:31,422 INFO Starting Nacos on nacos3 with PID 24 (/home/nacos/target/nacos-server.jar started by root in /home/nacos)

2020-06-17 14:06:31,444 INFO No active profile set, falling back to default profiles: default

2020-06-17 14:06:32,245 INFO Nacos is starting...

2020-06-17 14:06:33,299 INFO Nacos is starting...

2020-06-17 14:06:34,301 INFO Nacos is starting...
```

这个单机版的没问题
`docker-compose -f example/standalone-mysql.yaml up -d`

OS环境
```
>sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G3020
```

Docker环境
```
>docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by paderlol** [comment]
数据库没有启动成功，会有这个问题，有时候第一次启动因为docker探测到数据库的容器启动就会启动，并不会等数据库启动完成




在2020年06月17日 17:53，Leo Zhu 写道：

我在mac下启动nacos集群，按照以下命令，仓库克隆下来不做任何修改

git clone --depth 1 https://github.com/nacos-group/nacos-docker.git && cd nacos-docker



docker-compose -f example/cluster-hostname.yaml up -d



结果，nacos.log日志里重复出现这个，服务起不来，一直在不停重启

2020-06-17 14:06:31,226 INFO The server IP list of Nacos is [nacos1:8848, nacos2:8848, nacos3:8848]



2020-06-17 14:06:31,422 INFO Starting Nacos on nacos3 with PID 24 (/home/nacos/target/nacos-server.jar started by root in /home/nacos)



2020-06-17 14:06:31,444 INFO No active profile set, falling back to default profiles: default



2020-06-17 14:06:32,245 INFO Nacos is starting...



2020-06-17 14:06:33,299 INFO Nacos is starting...



2020-06-17 14:06:34,301 INFO Nacos is starting...



这个单机版的没问题
docker-compose -f example/standalone-mysql.yaml up -d

OS环境

>sw_vers

ProductName:	Mac OS X

ProductVersion:	10.14.6

BuildVersion:	18G3020



Docker环境

>docker version

Client: Docker Engine - Community

 Version:           19.03.8

 API version:       1.40

 Go version:        go1.12.17

 Git commit:        afacb8b

 Built:             Wed Mar 11 01:21:11 2020

 OS/Arch:           darwin/amd64

 Experimental:      false



Server: Docker Engine - Community

 Engine:

  Version:          19.03.8

  API version:      1.40 (minimum version 1.12)

  Go version:       go1.12.17

  Git commit:       afacb8b

  Built:            Wed Mar 11 01:29:16 2020

  OS/Arch:          linux/amd64

  Experimental:     false

 containerd:

  Version:          v1.2.13

  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429

 runc:

  Version:          1.0.0-rc10

  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd

 docker-init:

  Version:          0.18.0

  GitCommit:        fec3683

**Comment by paderlol** [comment]
它重启一段时间就会好了，不用在意这个

**Comment by leo18945** [comment]
我试了很多次还是不行，各个容量不停的重启，我等10分钟去看一次在重启，访问各个nacos实例的url不行，等到1个小时再去访问还是一样。

- 然后我就单独一个个启动服务，并把compose.yaml中三处 restart: always 注释掉
- 启动第一个服务
```
docker-compose -f example/cluster-hostname.yaml up -d mysql
docker-compose -f example/cluster-hostname.yaml up -d nacos1
```
访问 http://localhost:8848/nacos 正常
  
  
- 启动第二个服务
```
docker-compose -f example/cluster-hostname.yaml up -d nacos2
```
访问 http://localhost:8849/nacos 正常，但访问 http://localhost:8848/nacos 又打不开了，docker ps一看，nacos1实例挂了
  
  
- 启动第三个服务
```
docker-compose -f example/cluster-hostname.yaml up -d nacos3
```

访问 http://localhost:8850/nacos 正常，但访问 http://localhost:8848/nacos 
和 http://localhost:8849/nacos 都打不开了，docker ps一看，nacos1 和 nacos2 实例都挂了


- 并在 nacos.log 中看到以下报错
```
2020-06-18 21:09:54,805 INFO Completed initialization in 21 ms

2020-06-18 21:11:38,760 ERROR CONSOLE

java.lang.IllegalStateException: can not find peer: 172.16.238.11:8848
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore.receivedVote(RaftCore.java:434)
	at com.alibaba.nacos.naming.controllers.RaftController.vote(RaftController.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by yiqinghui** [comment]
docker ps，nacos1 和 nacos2 和 nacos3 都正常运行，也只有nacos1能访问。
我的内存全被占用了

**Comment by paderlol** [comment]
两个情况docker分配的内存不够，默认集群是每个节点需要2g内存，可以去扩大docker内存，分配6g左右，或者缩小Nacos每个节点内存，参考readme的参数

**Comment by hd-eujian** [comment]
集群模式在不停Nacos is starting

**Comment by dufuqiang** [comment]
内存不足就会一直重启，需要分配大一点的内存给

**Comment by gholay** [comment]
在mac系统环境中docker默认启动的容器使用的内存大小是2G， 可以修改默认docker容器启动使用内存大小 。
![image](https://user-images.githubusercontent.com/4527271/135383233-0c98f826-394d-4e52-8c80-f97e4ca6e91f.png)

**Comment by sunqb** [comment]
是内存的问题兄弟，内存不够了。集群模式需要的内存更多，可以通过启动参数看得到。
