### ISSUE TITLE
nacos/nacos:latest 支持连接8.0.x版本的MySQL吗,启动在报错

### ISSUE THREAD

**Issue by patience00** [nacos-group/nacos-docker#107]

**Comment by paderlol** [comment]
看下有个例子连接mysql8

**Comment by patience00** [comment]
> 看下有个例子连接mysql8

请问下要自己构建镜像吗,有现成的吗

**Comment by paderlol** [comment]
不需要自己构建镜像，里面是例子

**Comment by patience00** [comment]
你好,这是新拉一个MYSQL8的镜像呀,我环境中已经有MySQL了,利用现有的MySQL8,请问下需要怎么弄呢?

**Comment by paderlol** [comment]
你配置成你的外部连接就可以了，你看看readme里面已经说明了可以配置的环境变量啊

**Comment by paderlol** [comment]
把现有的mysql镜像去掉就行了

**Comment by patience00** [comment]
> 你配置成你的外部连接就可以了，你看看readme里面已经说明了可以配置的环境变量啊

之前就是配置了环境变量启动的,但是连接报错,MySQL版本是8.0.11,额

**Comment by patience00** [comment]
docker run --name nacos-standalone \
-e MODE=standalone \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=*******\
-e MYSQL_SERVICE_PORT=1*** \
-e MYSQL_SERVICE_DB_NAME=nacos \
-e MYSQL_SERVICE_USER=nacos \
-e MYSQL_SERVICE_PASSWORD=******  \
-e NACOS_AUTH_ENABLE=true \
-p 8848:8848 -d nacos/nacos-server:latest

**Comment by paderlol** [comment]
你挂了mysql 8驱动吗？要挂卷把驱动挂上，所以我让你看mysql8的例子

**Comment by patience00** [comment]
> 你挂了mysql 8驱动吗？要挂卷把驱动挂上，所以我让你看mysql8的例子

有MySQL8的驱动了,请问挂载哪个目录?

**Comment by paderlol** [comment]
我写的mysql8例子里面有的，看下那个yaml文件

**Comment by patience00** [comment]
可以了,把mysql8的驱动jar包放到宿主机的/home/mysql
docker run --name nacos-standalone  \
-e MODE=standalone  \
-e SPRING_DATASOURCE_PLATFORM=mysql  \
-e MYSQL_SERVICE_HOST=MySQL_IP \
-e MYSQL_SERVICE_PORT=3306  \
-e MYSQL_SERVICE_DB_NAME=nacos \
-e MYSQL_SERVICE_USER=nacos \
-e MYSQL_SERVICE_PASSWORD=PWD  \
-e NACOS_AUTH_ENABLE=true \
-v /home/mysql:/home/nacos/plugins/mysql  \
-p 8848:8848 -d nacos/nacos-server:latest

**Comment by patience00** [comment]
可以了,把mysql8的驱动jar包放到宿主机的/home/mysql
docker run --name nacos-standalone \\
-e MODE=standalone \\
-e SPRING_DATASOURCE_PLATFORM=mysql \\
-e MYSQL_SERVICE_HOST=MySQL_IP \\
-e MYSQL_SERVICE_PORT=3306 \\
-e MYSQL_SERVICE_DB_NAME=nacos \\
-e MYSQL_SERVICE_USER=nacos \\
-e MYSQL_SERVICE_PASSWORD=PWD \\
-e NACOS_AUTH_ENABLE=true \\
-v /home/mysql:/home/nacos/plugins/mysql \\
-p 8848:8848 -d nacos/nacos-server:latest

**Comment by patience00** [comment]
非常感谢
