### ISSUE TITLE
nacos集群版启动失败2020-06-20 15:48:52,475 ERROR [db-error] master db 192.168.123.88 down  [master-db] master db not found.

### ISSUE THREAD

**Issue by git-yo** [nacos-group/nacos-docker#108]
docker启动文件，其他三个节点类似，mysql为单机版mysql5.6
version: '3' 
services:
  # nacos-server服务注册与发现，配置中心服务    
  docker-nacos-server:
    image: nacos/nacos-server:latest
    container_name: nacos-server-1
    ports:
      - "8848:8848"
      - "9555:9555"
    networks: 
      - nacos_net
    restart: on-failure
    privileged: true
    environment:
      PREFER_HOST_MODE: ip #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      SPRING_DATASOURCE_PLATFORM: mysql #数据源平台 仅支持mysql或不保存empty
      NACOS_SERVER_IP: 192.168.123.88 #多网卡情况下，指定ip或网卡
      NACOS_SERVERS: 192.168.123.88:8848 192.168.123.89:8848 192.168.123.90:8848 #集群中其它节点[ip1:port ip2:port ip3:port]
      MYSQL_DATABASE_NUM: 1
      MYSQL_SERVICE_HOST: 192.168.123.88
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos1
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: passwo@123#!
      #JVM调优参数
      JVM_XMS: 4g  #-Xms default :2g
      JVM_XMX: 4g  #-Xmx default :2g
      JVM_XMN: 2g  #-Xmn default :1g
      #JVM_MS:   #-XX:MetaspaceSize default :128m
      #JVM_MMS:  #-XX:MaxMetaspaceSize default :320m
      NACOS_DEBUG: y #是否开启远程debug，y/n，默认n
      #TOMCAT_ACCESSLOG_ENABLED: true #是否开始tomcat访问日志的记录，默认false
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs #日志输出目录
      - ../init.d/custom.properties:/home/nacos/init.d/custom.properties #../init.d/custom.properties内包含很多自定义配置，可按需配置

networks:
  nacos_net:
    driver: bridge

启动报错config-fatal.log日志文件：
2020-06-20 15:53:42,539 ERROR [db-error] master db 192.168.123.88 down.

2020-06-20 15:53:42,539 ERROR [master-db] master db not found.

mysql能够通过宿主机正常登录

nacos.log日志文件报错：
2020-06-20 15:48:23,861 ERROR Nacos failed to start, please see /home/nacos/logs/nacos.log for more details.

2020-06-20 15:48:23,873 INFO

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2020-06-20 15:48:23,878 ERROR Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'opsController' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-1.2.0.jar!/com/alibaba/nacos/config/server/controller/OpsController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set

**Comment by paderlol** [comment]
Sql脚本没有初始化吧

**Comment by zhygit0610** [comment]
好的，我把代码拉下来后没有看到有sql脚本呢，需要在哪里下载sql脚本呢？谢谢

**Comment by zhygit0610** [comment]
谢谢，解决了。找到地址了： https://github.com/alibaba/nacos/blob/master/distribution/conf/nacos-mysql.sql
