### ISSUE TITLE
What is the password of the admin user of version 0.8.0?

### ISSUE THREAD

**Issue by qq12157138** [nacos-group/nacos-docker#11]
password: $2a$10$HxtJtd59imujvbux.i55zOGewhnJiLVXX8D9AETDMV.XtBLDGOXtW

What is the corresponding password?

How do I add other users and passwords? What is the encryption rule?

**Comment by paderlol** [comment]
> password: $2a$10$HxtJtd59imujvbux.i55zOGewhnJiLVXX8D9AETDMV.XtBLDGOXtW
> 
> What is the corresponding password?
> 
> How do I add other users and passwords? What is the encryption rule?

Q1:What is the corresponding password?
A1:The default password is **nacos**

Q2:How do I add other users and passwords? What is the encryption rule?
A2:you can check out answer from here [nacos-console-guide](https://nacos.io/en-us/docs/console-guide.html)

**Comment by qq12157138** [comment]
我在dockerhub上搜索到的nacos镜像，这不是属于你们的吗？我用这个镜像启动后，我用nacos账户登录mysql数据库后查看user表发现登录用户是admin，密码不是nacos。

**Comment by paderlol** [comment]
刚刚pull的镜像吗，nacos/nacos-server


| |
浮夸
|
|
邮箱：huangmnlove@163.com
|

签名由 网易邮箱大师 定制

On 01/24/2019 20:00, Peter wrote:

我在dockerhub上搜索到的nacos镜像，这不是属于你们的吗？我用这个镜像启动后，我用nacos账户登录mysql数据库后查看user表发现登录用户是admin，密码不是nacos。

**Comment by qq12157138** [comment]
@paderlol 我刚搜了下，看nacos-mysql-master的更新时间是2天前，你确定这是对的？我现在用的nacos-mysql-master镜像的创建时间是47小时前。

**Comment by qq12157138** [comment]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/15812485/51719599-0baae880-2085-11e9-9e1c-37e400433020.png">

**Comment by paderlol** [comment]
是的,我昨天确认过了这个问题,你可能是因为本地的mysql卷没有清除,所以导致更新了也还是用的以前的db文件,建议你删除以下mysql的挂载卷,重新试一下,可以在example目录下执行这个命令
```shell
sudo rm -rf mysql-*
```
下面这是我刚刚重新验证的数据库截图
![screenshot from 2019-01-25 10-02-49](https://user-images.githubusercontent.com/7919984/51720425-77db1b80-2088-11e9-987c-9589badc0f7a.png)

**Comment by qq12157138** [comment]
@paderlol 果然是这个原因，谢谢。

**Comment by paderlol** [comment]
客气了 应该的

**Comment by qq12157138** [comment]
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/15812485/51720610-575f9100-2089-11e9-8bfa-fe78ecf70f9e.png">
我用navicat连接mysql后Comment那都是乱码，这是因为navicat客户端导致的还是什么

**Comment by paderlol** [comment]
你这个重新提个issue吧 是数据库本身的原因
