### ISSUE TITLE
arm64 平台支持

### ISSUE THREAD

**Issue by tulid** [nacos-group/nacos-docker#110]
请问，可以将nacos-mysql-master和nacos-mysql-slave的dockerfile及其相关文件放到github上吗？我在部署nacos到arm64环境时会因为mysql的问题无法部署，谢谢

**Comment by paderlol** [comment]
现在我已经移除掉nacos mysql master和slave了

**Comment by tulid** [comment]
请问一下，在哪里更新了呢，我在阿里云应用商店没有看到最新的更新版，麻烦您告知一下，感谢





jinquan.wu
jinquan.wu@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pader"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 晚上6:21
收件人:&nbsp;"nacos-group/nacos-docker"<nacos-docker@noreply.github.com&gt;;
抄送:&nbsp;"ghost"<1183743631@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nacos-group/nacos-docker] arm64 平台支持 (#110)





 
现在我已经移除掉nacos mysql master和slave了

**Comment by paderlol** [comment]
1.1.4以后，还有我解释下除了nacos以外的镜像都是我临时做例子方便做的镜像，不是用于生产的

**Comment by zqr95518** [comment]
请问一下，有提供arm版本的nacos的docker镜像么，example里没找到。

**Comment by seepine** [comment]
求支持arm镜像，我自己clone构建报错了
```
seepine@Mac-mini build % docker build -t seepine/nacos-server:2.0.3-arm .
[+] Building 77.8s (3/3) FINISHED                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 37B                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => ERROR [internal] load metadata for docker.io/library/centos:7.5.1804                                                                              77.7s
------
 > [internal] load metadata for docker.io/library/centos:7.5.1804:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:7a45e4a1efbaafc1d9aa89925b6fdb33288a96d35ea0581412316e2f0ad3720a: not found
```

**Comment by zchazc** [comment]
@seepine @zqr95518 我自己整树莓派时改了个，需要的可以试试，修改的地方也标明了，有出入可以自己改下：
[dockerhub-link](https://hub.docker.com/r/zchazc/nacos-server-arm64)

**Comment by anson0370** [comment]
还是希望官方能支持一下，直接打双架构镜像。

**Comment by paderlol** [comment]
Fixed #257

**Comment by MingningShao** [comment]
Seems still no ARM image available...
