### ISSUE TITLE
Getting Error while starting nacos-standalone-mysql

### ISSUE THREAD

**Issue by aman1403** [nacos-group/nacos-docker#112]
I am trying to start nacos service from docker by using this command:-
           ` docker-compose -f example/standalone-mysql-8.yaml up`
But, I am getting error while starting nacos-standalone-mysql. Please find the screenshot of the error below for reference.

![image](https://user-images.githubusercontent.com/45468560/87127921-64d3ff80-c2ac-11ea-93e4-4e2f6a0974df.png)

**Comment by githubwyj** [comment]
看下 init.d 目录下的文件，custom.properties 变成了目录
