### ISSUE TITLE
控制台历史版本js异常

### ISSUE THREAD

**Issue by LikeGuo** [nacos-group/nacos-docker#113]
配置管理->历史版本 输入dataId group DEFAULT_GROUP，点击查询，页面空白
同这个issue，https://github.com/alibaba/nacos/issues/2453
环境：
nacos-server:1.2.0和1.2.1

**Comment by paderlol** [comment]
这个issue 三月份就修复了，我5月还发过镜像，你确定是这个问题吗？

**Comment by LikeGuo** [comment]
确定。使用非镜像安装是ok的。修复后的是哪个版本呢？

**Comment by paderlol** [comment]
如果是在1.2.1修复的那应该就在1.2.1或者1.3.0上面，我已经刚刚重新发了1.2.1和1.2.0

**Comment by LikeGuo** [comment]
pull了1.3.0问题依然存在啊。你有空看是否能重现下。解决了在这里回复下，谢谢。

**Comment by paderlol** [comment]
> pull了1.3.0问题依然存在啊。你有空看是否能重现下。解决了在这里回复下，谢谢。
你好,麻烦重新pull一下镜像确认现在是否有问题,我已经都重新发布镜像了
