### ISSUE TITLE
启动后多出一个节点,并且一直去链接

### ISSUE THREAD

**Issue by iqunqunqun** [nacos-group/nacos-docker#115]
配置文件只有三个内网节点，但集群运行后却会去连接一个没有配置的节点，请问是为什么？？

```
# 部署的节点信息
INFO The server IP list of Nacos is [192.168.122.128:8848, 192.168.122.128:8849, 192.168.122.130:8848]

# 多出的节点报错
java.lang.IllegalStateException: can not find peer: 172.18.0.3:8848
```

**Comment by paderlol** [comment]
你这是用的哪个启动的，感觉像是多网卡啊，因为docker的ip应该是172的才对

**Comment by iqunqunqun** [comment]
> 你这是用的哪个启动的，感觉像是多网卡啊，因为docker的ip应该是172的才对

使用的虚拟机，上面的地址是虚拟机的IP地址

**Comment by iqunqunqun** [comment]
> > 你这是用的哪个启动的，感觉像是多网卡啊，因为docker的ip应该是172的才对
> 
> 使用的虚拟机，上面的地址是虚拟机的IP地址

![image](https://user-images.githubusercontent.com/38368997/87938361-0affe080-cac9-11ea-8923-0d64ddd89f31.png)

**Comment by paderlol** [comment]
你的cluster配置文件怎么写的？

**Comment by iqunqunqun** [comment]
> 你的cluster配置文件怎么写的？

![image](https://user-images.githubusercontent.com/38368997/87938602-68942d00-cac9-11ea-8aca-019cca142a31.png)
![image](https://user-images.githubusercontent.com/38368997/87938669-806bb100-cac9-11ea-9a71-4d8c42ba5c34.png)
![image](https://user-images.githubusercontent.com/38368997/87938679-8497ce80-cac9-11ea-8b72-8277932ea111.png)

**Comment by iqunqunqun** [comment]
> 你的cluster配置文件怎么写的？

![image](https://user-images.githubusercontent.com/38368997/87938809-b14be600-cac9-11ea-9fa8-f404076d0d74.png)
![image](https://user-images.githubusercontent.com/38368997/87938840-bc067b00-cac9-11ea-88b9-af34f1077da6.png)
![image](https://user-images.githubusercontent.com/38368997/87938866-c3c61f80-cac9-11ea-817b-631044e9ec3d.png)

**Comment by paderlol** [comment]
你这应该是多网卡导致的，你试下用NACOS_SERVER_IP指定每个节点的ip，比如192.168.22.1 是第一个虚拟机，那么就配置NACOS_SERVER_IP是这个ip，不然他获取的是docker的容器的ip去匹配

**Comment by iqunqunqun** [comment]
> 你这应该是多网卡导致的，你试下用NACOS_SERVER_IP指定每个节点的ip，比如192.168.22.1 是第一个虚拟机，那么就配置NACOS_SERVER_IP是这个ip，不然他获取的是docker的容器的ip去匹配

谢谢你，加了NACOS_SERVER_IP后完美解决

**Comment by a350844866** [comment]
如果是K8S部署的话，并不知道节点id呀，只能用服务名指定，也出现了你这个问题要怎么解决

**Comment by jackyting825** [comment]
> 如果是K8S部署的话，并不知道节点id呀，只能用服务名指定，也出现了你这个问题要怎么解决

同问,怎么处理的?感谢
