### ISSUE TITLE
集群3节点无限重启，2节点可以使用

### ISSUE THREAD

**Issue by ztqer** [nacos-group/nacos-docker#116]
### 使用hostname或ip启动nacos-docker集群后无法访问控制台
1. 查看日志发现各节点在不断重启  
2. 访问控制台有登陆界面响应，但登陆被拒绝，提示为密码错误
3. 检查mysql表数据正常
4. 通过docker停止任一容器后，其他节点均可访问控制台并登陆成功

**Comment by paderlol** [comment]
Mac？

**Comment by paderlol** [comment]
Docker内存不够会这样

**Comment by ztqer** [comment]
> Docker内存不够会这样
确实是这个问题，我调整了docker的内存限制就可以了，非常感谢
