### ISSUE TITLE
9555:9555

### ISSUE THREAD

**Issue by renshengwuhui** [nacos-group/nacos-docker#117]
请问下为何需要开放这个端口？作用是什么？谢谢！

**Comment by paderlol** [comment]
例子里面开放是为了远程调试方便，默认是关闭的

**Comment by renshengwuhui** [comment]
但是没有看到哪里调试需要此端口，看到集群里只有一开放了此端口，更有点奇怪，想了解下我们做什么时会用到这个端口？多谢啦

**Comment by paderlol** [comment]
调试错误，就是类似tomcat远程调试，例子写了一个，但是只有集群有这个功能，主要是调试代码，nacos的代码

**Comment by renshengwuhui** [comment]
好的，多谢
