### ISSUE TITLE
Standalone Mysql  Command IN README.md  FileNotFoundError

### ISSUE THREAD

**Issue by dupengcheng** [nacos-group/nacos-docker#118]
* Standalone Mysql

  ```powershell
  docker-compose -f example/standalone-mysql.yaml up
  ```

ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './example/standalone-mysql.yaml'

**Comment by paderlol** [comment]
现在这个例子带版本了，可能readme没更新
