### ISSUE TITLE
无法新建namespace

### ISSUE THREAD

**Issue by dmnotdm** [nacos-group/nacos-docker#119]
standalone-mysql-8.yaml启动
新建namespace报错
org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'customNamespaceId' is not present
试了一下貌似1.3.1都会报错

**Comment by paderlol** [comment]
这个似乎是Nacos本身的问题？你是在控制台新建nanespace出问题吗？

**Comment by paderlol** [comment]
我这边尝试是没有问题的
