### ISSUE TITLE
nacos v.1.3.2配置中心不刷新

### ISSUE THREAD

**Issue by youshang520i** [nacos-group/nacos-docker#120]
**nacos服务修改配置，本地项目不会刷新最新配置**
1. 集群会刷新
2. 单机不会刷新

**docker-compose 文件**
version: "3"
services:
  nacos_service:
    image: 'nacos/nacos-server:1.3.2'
    container_name: nacons_service
    restart: always
    ports:
      - '8848:8848'
    hostname: nacos_service
    environment:
      - PREFER_HOST_MODE=hostname
      - TZ=Asia/shanghai
      - MODE=standalone
      - NACOS_APPLICATION_PORT=8848
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=128m
      - NACOS_AUTH_ENABLE=false
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.3.***
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
  sentinel_server:
    image: bladex/sentinel-dashboard
    container_name: sentinel_server
    ports:
      - '8858:8858'

**Comment by paderlol** [comment]
需要更多信息,我暂时测试没有出现这个问题
