### ISSUE TITLE
mysql在nacos启动之后运行,  那么nacos容器不会自动重启

### ISSUE THREAD

**Issue by Yogurt-lei** [nacos-group/nacos-docker#123]
例如 mysql在nacos启动之后运行,  那么nacos容器不会自动重启

**Comment by paderlol** [comment]
你可以自己设置restart always，并且这个是例子，只是给大家演示功能，具体生产或者工作环境数据库怎么配置，看你们自己的

**Comment by Yogurt-lei** [comment]
是设置了restart always nacos 报不能连接数据库异常，但是并没有触发重启

**Comment by paderlol** [comment]
那可能是数据库连接失败并没有导致，系统启动出问题

**Comment by paderlol** [comment]
这个可能需要自己重启一次，compose文件就好了，因为只有第一次，有这个问题吧

**Comment by Yogurt-lei** [comment]
对的 只有第一次会出现这个问题 只要能触发异常  容器自动重启就好了:( ， 我现在是写脚本检测mysql启动后启动nacos
