### ISSUE TITLE
Nacos cant start with error log: No DataSource set

### ISSUE THREAD

**Issue by eph6666** [nacos-group/nacos-docker#124]
### 环境：
kubernetes 1.16 in aws eks
mysql 5.7.30 aws rds
### 问题描述：
pod可以启动，但无正常启动的日志，进入容器看 logs/nacos.log显示如下报错
`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configOpsController' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-1.3.2.jar!/com/alibaba/nacos/config/server/controller/ConfigOpsController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)`
测试在pod内可以使用mysql client和同样的配置连接mysql

**Comment by paderlol** [comment]
请问你怎么配置数据库的？

**Comment by paderlol** [comment]
还有请自己建好数据表

**Comment by eph6666** [comment]
是的，需要手动建表，已经起来了
建表sql文件：
https://github.com/alibaba/nacos/edit/master/distribution/conf/nacos-mysql.sql

**Comment by paderlol** [comment]
那我关闭issue了
