### ISSUE TITLE
网络没问题，启动没报错，页面就是不响应，docker单机模式启动

### ISSUE THREAD

**Issue by sc2885112** [nacos-group/nacos-docker#126]
无法访问此网站******* 的响应时间过长。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_TIMED_OUT

**Comment by paderlol** [comment]
你看下容器里面如果能访问就是你docker容器网络的问题，还有看下日志文件

**Comment by sc2885112** [comment]
重新git clone
重新docker-compose -f example/standalone-derby.yaml up 又可以了。。。。。

**Comment by sc2885112** [comment]
确实是docker网络的问题,自建的docker network好像有点问题，正在排查，感谢！

**Comment by sc2885112** [comment]
是因为创建了一个自建的docker network 没有添加响应的主机网卡,类似于docker自带的docker0网卡,所有网络不通,以后有遇到类似情况的朋友可以参考一下

**Comment by liuguoyu** [comment]
> 是因为创建了一个自建的docker network 没有添加响应的主机网卡,类似于docker自带的docker0网卡,所有网络不通,以后有遇到类似情况的朋友可以参考一下

默认应该使用的是brige网桥，与宿主机没有映射吗？
我查了半天已经到IPV6的问题，还没有确诊。。。

**Comment by liuguoyu** [comment]
> > 是因为创建了一个自建的docker network 没有添加响应的主机网卡,类似于docker自带的docker0网卡,所有网络不通,以后有遇到类似情况的朋友可以参考一下
> 
> 默认应该使用的是brige网桥，与宿主机没有映射吗？ 我查了半天已经到IPV6的问题，还没有确诊。。。

<img width="848" height="77" alt="Image" src="https://github.com/user-attachments/assets/9234314e-efe8-4c12-940e-1acbcd6553de" />
看输出是容器内仅监听ipv6端口，保证ipv4可以访问ipv6即可（net.ipv6.bindv6only=0）
