### ISSUE TITLE
docker compose无限重复下载

### ISSUE THREAD

**Issue by todother** [nacos-group/nacos-docker#127]
按照官方文档，使用docker compose安装镜像时，无限重复下载安装过程。

当所有显示为download complete后，大约5秒后会刷新当前状态，重新进行下载所有内容。请检查是否存在某些校验问题，谢谢。

当前使用ubuntu虚拟机，mac均出现该问题。

docker-compose -f example/standalone-derby.yaml up

**Comment by paderlol** [comment]
这个很可能是你自己网络问题，导致不停重试，nacos docker只是镜像而已不会影响到pull 或者push的

**Comment by todother** [comment]
> 这个很可能是你自己网络问题，导致不停重试，nacos docker只是镜像而已不会影响到pull 或者push的

不好意思，还得请教一下，因为已经配置了国内源，其他的镜像下载均无问题，比如docker compose中的prom/prometheus，唯独nacos server一直出现问题。

具体表现为

 **5ad559c5ae16: Downloading**  （其余均为download complete）

 **error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/ef/ef8e53226440e8e2d6298e37bcf76a8b704cf7cc54e451a4ea03a83d70764773/data?verify=1599722281-MitBfRPnxmw9bkH6siIxnPzyG%2FI%3D: net/http: TLS handshake timeout**

请问是否有什么解决方法？还望不吝赐教，谢谢。

**Comment by paderlol** [comment]
这个是说你拉其中某一个层拉不到，超时了，我本地有Ubuntu也有mac都没问题

**Comment by paderlol** [comment]
你可以试着切换别的国内镜像，我本地就是用的官方的仓库镜像地址
