### ISSUE TITLE
单机模式下docker-compose连接自定义mysql5.7数据库出现JDBC连接异常

### ISSUE THREAD

**Issue by lzlongqiao** [nacos-group/nacos-docker#131]
### 一.异常信息
在连接数据库时,出现了异常信息: 

Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: 
The server time zone value 'ÖÐ¹ú±ê×¼Ê±¼ä' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

也就是说,出现了mysql的无效连接属性异常：服务器时区值无法辨认或表示多个时区，如果你想使用时区支持，你必须通过服务器时区配置属性来配置服务器或JDBC驱动从而使用更具体的时区值。

### 二.异常原因
这是因为 mysql升级到8.0及以上，添加了许多新特性，安全性也得到提升。当然操作时也增加了些繁琐，需要考虑到的时区问题便是其中之一。

**Comment by paderlol** [comment]
数据库时区 目前已经在1.4.0版本添加了 jdbc url参数自定义
