### ISSUE TITLE
增加环境变量更改默认登录用户名及密码

### ISSUE THREAD

**Issue by xfengfeng** [nacos-group/nacos-docker#132]
我当前使用的环境是：mysql standalone docker部署

能不能增加个docker启动参数（环境变量），用于修改默认的登录用户名及密码？
在批量部署的时候，而且要求各个实例密码不同时就很有用了。

**Comment by paderlol** [comment]
这个需要提单Nacos支持这个功能，我这边就可以配置

**Comment by liuzhenji** [comment]
> 我当前使用的环境是：mysql standalone docker部署
> 
> 能不能增加个docker启动参数（环境变量），用于修改默认的登录用户名及密码？
> 在批量部署的时候，而且要求各个实例密码不同时就很有用了。

现在的账号是naocs，我从数据库看的；但是密码是多少？数据密码存储的是加密后的；我尝试nacos/nacos也不行

**Comment by paderlol** [comment]
这个诉求应该提到Nacos主仓库，因为密码都是盐加密的，默认密码就是nacos。

**Comment by liuzhenji** [comment]
> 这个诉求应该提到Nacos主仓库，因为密码都是盐加密的，默认密码就是nacos。

嗯，我查的nacos官网，确实是nacos/nacos。奇怪了。。。我在k8s上部署的，nacos/nacos登陆不了

**Comment by paderlol** [comment]
登录不鸟 很可能是启动错误了,可以看下是否启动错误了

**Comment by liuzhenji** [comment]
> 登录不鸟 很可能是启动错误了,可以看下是否启动错误了

谢啦。我直接从数据库把密码重置了。。。

**Comment by paderlol** [comment]
ok 那暂时关闭这个issue了
