### ISSUE TITLE
勒索

### ISSUE THREAD

**Issue by tony3154** [nacos-group/nacos-docker#137]
https://hub.docker.com/r/nacos/nacos-server/tags
这个地址上拉取1.3.2中了勒索，有其他人中招吗？

**Comment by paderlol** [comment]
1.3.2勒索是指什么？

**Comment by paderlol** [comment]
你是否自己的docker守护进程被侵入了？

**Comment by tony3154** [comment]
防火墙没有开放出去，所以怀疑是docker上面的镜像有问题，数据库被掏空，被勒索了。

**Comment by paderlol** [comment]
Nacos的镜像全部是由hub自动build，并且获取的Nacos官方release打包构建，有构建日志，有构建历史，至于数据库，你们应该也是用的自己的，所以如果有确凿的说法指向是镜像问题请贴出来，不然你这样的说法会引起没必要的恐慌。

**Comment by tony3154** [comment]
不好意思，我就是确定不了原因，所以来问问，有困扰，我删掉

**Comment by paderlol** [comment]
嗯，建议还是先排查是否数据库已经被注入了
