### ISSUE TITLE
如何修改jvm参数

### ISSUE THREAD

**Issue by yiqinghui** [nacos-group/nacos-docker#139]
git clone https://github.com/nacos-group/nacos-docker.git
cd nacos-docker
docker-compose -f example/cluster-hostname.yaml up 

云服务器是2核4g，启动后内存几乎全被占用。
所以想修改jvm参数，把容器、镜像全都删除后，修改 DockerFile、docker-startup.sh：Xms、Xmx 全都改成256m。
重新运行：docker-compose -f example/cluster-hostname.yaml up 
发现并不是按照自己设置的256m运行的，还是按照 2g 来运行的。

应该怎么修改jvm参数？

**Comment by paderlol** [comment]
这个是java的特性导致无法设立特性，可以设置java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap 来解决，具体原因自行Google查看

**Comment by yiqinghui** [comment]
> 这个是java的特性导致无法设立特性，可以设置java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap 来解决，具体原因自行Google查看

你好，请问这个是在哪设置？
能截个图，或者详细说明一下吗？
我在 docker-startup.sh 中添加了你说的配置，发现仍然没有效果。

![image](https://user-images.githubusercontent.com/23735927/99162904-2a88dc00-273e-11eb-9b36-278ec032cd19.png)
![image](https://user-images.githubusercontent.com/23735927/99162911-38d6f800-273e-11eb-9766-8405efda95f9.png)

**Comment by paderlol** [comment]
你修改文件了，你有重新编译自己的镜像吗？而且你修改文件都写的是错的，我用的脚本的环境变量方式，你直接改成${256m}，shell无法都不对。
其次修改这个内存直接通过在docker compose文件配置环境变量就行了，具体Readme的属性列表都有。
