### ISSUE TITLE
mac pro 上显示版本为0.6

### ISSUE THREAD

**Issue by nodejsnewbie** [nacos-group/nacos-docker#141]
MacBook Pro (Retina, 13-inch, Early 2015)
MacOS Catalina 10.15.7 
按照英文redme克隆后执行docker-compose -f example/standalone-mysql-5.7.yaml up   
浏览器进入发现是0.6版本

**Comment by paderlol** [comment]
可以看下镜像引用的版本,然后清除下浏览器缓存
