### ISSUE TITLE
nacos 1.3.2 和1.4.0 集群修改对外暴露端口导致集群节点异常。

### ISSUE THREAD

**Issue by yszansx** [nacos-group/nacos-docker#143]
version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:1.4.0
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8849:8848"
      - "9555:9555"
    environment:
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
      - MYSQL_SERVICE_HOST=127.0.0.1
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=123456
    restart: on-failure
  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:1.4.0
    container_name: nacos2
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8850:8848"
    environment:
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
      - MYSQL_SERVICE_HOST=127.0.0.1
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=123456
    restart: on-failure
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:1.4.0
    container_name: nacos3
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8851:8848"
    environment:
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
      - MYSQL_SERVICE_HOST=127.0.0.1
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=123456
    restart: on-failure

如上：docker-compose 文件。经过测试1.3.2 和1.4.0 版本nacos1 端口修改为8849对外映射，会导致集群节点至少一个处于candidate状态，修改nacos1为8848端口后集群节点恢复正常。希望改进下。

**Comment by paderlol** [comment]
你改的容器端口吗？还是宿主机端口？宿主机端口改了，只要不是改集群文件配置得端口就不会有问题

**Comment by yszansx** [comment]
![image](https://user-images.githubusercontent.com/43443722/99625007-3b04c380-2a6a-11eb-90e1-240292495a1c.png)
宿主机的端口 如图，会导致集群节点至少一个处于candidate状态 百分百复现。

**Comment by yszansx** [comment]
1.2.1和1.3.0 可以正常。升级的时候发现的这个问题。

**Comment by yszansx** [comment]
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                            NAMES
d53c2f6d02f7        nacos/nacos-server:1.3.2   "bin/docker-startup.…"   2 hours ago         Up 2 hours          0.0.0.0:9555->9555/tcp, 0.0.0.0:8849->8848/tcp   nacos1
f7bc1c320d39        nacos/nacos-server:1.3.2   "bin/docker-startup.…"   2 hours ago         Up 2 hours          0.0.0.0:8850->8848/tcp                           nacos2
85aff039f618        nacos/nacos-server:1.3.2   "bin/docker-startup.…"   2 hours ago         Up 2 hours          0.0.0.0:8851->8848/tcp                           nacos3

这样启动就会有问题 ，nacos1 对外映射的端口必须改为0.0.0.0:8848->8848/tcp 才能恢复正常。

**Comment by paderlol** [comment]
这个似乎是内部选举的问题，你有试过不用镜像吗？

**Comment by yszansx** [comment]
源码部署只试过单节点的。集群没试过。

**Comment by paderlol** [comment]
那这个issue需要提到nacos，因为可能是集群选主的问题

**Comment by yszansx** [comment]
好的。

**Comment by dennsya** [comment]
> 那这个issue需要提到nacos，因为可能是集群选主的问题

1.4.0的镜像集群选举确实有问题，经过测试，只有按照官方的文档，把三台nacos安装在一台才正常。如果分别安装到三台主机，那么注册服务不同步，且只有一台可以注册服务，我测试好多遍了

**Comment by paderlol** [comment]
不在一台的话需要对外开放7848这个端口，这是raft选举需要用到的

**Comment by dennsya** [comment]
> 不在一台的话需要对外开放7848这个端口，这是raft选举需要用到的

1.3.0不需要暴露7848端口吗？

**Comment by dennsya** [comment]
> 不在一台的话需要对外开放7848这个端口，这是raft选举需要用到的

谢谢，确实是这个问题，我暴露7848端口，1.4.0集群就正常了,而1.3.0的版本不需要暴露7848

**Comment by paderlol** [comment]
Ok，我后面发新版本会把这个加入demo里面

**Comment by z514987467** [comment]
docker部署，能修改对外暴露的7848断开吗
