### ISSUE TITLE
docker集群版按照步骤来跑不起来

### ISSUE THREAD

**Issue by 410919244** [nacos-group/nacos-docker#15]
![image](https://user-images.githubusercontent.com/20715540/51962201-40aaa700-249a-11e9-907d-ea6789bf3dd6.png)

临时买了台阿里的ECS，执行命令：docker-compose -f example/cluster-hostname.yaml up 
启动时： Access denied for user 用户访问被拒绝。
貌似没跑起来。

**Comment by paderlol** [comment]
第一次启动是会有这个问题,因为从库连接主库失败后要等60秒再会去重新确定,而nacos有个探针会检测从库是否存活,这个不会影响nacos是否启动了

**Comment by paderlol** [comment]
而且你的日志里面后面一段已经显示连接上主库了,麻烦去确认控制台是否启用.
