### ISSUE TITLE
配置mysql端口不生效

### ISSUE THREAD

**Issue by 965114346** [nacos-group/nacos-docker#151]
只能使用默认MySQL端口3306，配置其他端口会连接不上数据库

**Comment by paderlol** [comment]
…你是不是自己配置错了，一直在改内部端口

**Comment by 965114346** [comment]
> …你是不是自己配置错了，一直在改内部端口

`version: '3'
services:
  mysql57:
    container_name: mysql57
    image: nacos/nacos-mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos_config
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    environment:
      #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      PREFER_HOST_MODE: hostname
      MODE: standalone
      #数据源平台 仅支持mysql或不保存empty
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql57
      MYSQL_SERVICE_PORT: 3308
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql57
    restart: on-failure`
就一个docker-compose.yml，不会吧

**Comment by 965114346** [comment]
> …你是不是自己配置错了，一直在改内部端口

**version: '3'
services:
  mysql57:
    container_name: mysql57
    image: nacos/nacos-mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos_config
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    environment:
      #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      PREFER_HOST_MODE: hostname
      MODE: standalone
      #数据源平台 仅支持mysql或不保存empty
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql57
      MYSQL_SERVICE_PORT: 3308
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql57
    restart: on-failure**

**Comment by paderlol** [comment]
你改个宿主机的端口，这里上面的host配置的是内部容器的host

**Comment by 965114346** [comment]
> 你改个宿主机的端口，这里上面的host配置的是内部容器的host

跟host没关系，这里我把端口都改成3306的没问题，改成3308的就连不上

**Comment by paderlol** [comment]
这个MYSQL_SERVICE_HOST: mysql57指向的是容器里面的host，你一直改的是宿主机映射端口，你说有问题没有？

**Comment by 965114346** [comment]
> 这个MYSQL_SERVICE_HOST: mysql57指向的是容器里面的host，你一直改的是宿主机映射端口，你说有问题没有？

我明白了，谢谢
