### ISSUE TITLE
请升级nacos的版本到1.4.1，解决权限漏洞

### ISSUE THREAD

**Issue by duan847** [nacos-group/nacos-docker#154]
如题。

**Comment by chaiyd** [comment]
可以参考，已经申请合并了，但是还没有通过
GitHub： https://github.com/chaiyd/nacos-docker/blob/master/build/Dockerfile-debian10
docker hub ： docker pull chaiyd/nacos:1.4.1

**Comment by paderlol** [comment]
已经升级到1.4.1了 并且发布了

**Comment by paderlol** [comment]
@chaiyd 1.4.1对脚本有改动的 修复了Nacos Server端配置读取的问题,另外增加了权限参数

**Comment by chaiyd** [comment]
> @chaiyd 1.4.1对脚本有改动的 修复了Nacos Server端配置读取的问题,另外增加了权限参数

好的，已经重新合并了
