### ISSUE TITLE
为什么显示的是控制台版本显示的是0.6.0

### ISSUE THREAD

**Issue by wonglay** [nacos-group/nacos-docker#158]
> 你用的什么tag是什么？然后版本是说控制台？如果你以前用过0.6的nacos，自己注意清除浏览器缓存

解决了，是浏览器缓存的问题

**Comment by paderlol** [comment]
你用的什么tag是什么？然后版本是说控制台？如果你以前用过0.6的nacos，自己注意清除浏览器缓存

**Comment by Ostaer** [comment]
更新下文档？

是中文的Readme文档中，有一种方式会拉取0.6版本的nacos启动

 https://github.com/nacos-group/nacos-docker/blob/master/README_ZH.md

## 其他使用方式

打开命令窗口执行：

* Clone 项目 并且进入项目根目录

  ```powershell
  git clone https://github.com/paderlol/nacos-docker.git    这是0.6版本
  cd nacos-docker
  ```
