### ISSUE TITLE
docker 部署nacos

### ISSUE THREAD

**Issue by kingslyChen** [nacos-group/nacos-docker#16]
本地跑nacos 和config 是没问题的，docker 部署了nacos config就不起作用了，是不是要配置其他东西？

**Comment by paderlol** [comment]
请问你是怎么启动的 能否说一下详细的信息

**Comment by zac-fbt** [comment]
我也遇到了这个问题，使用docker-compose -f example/standalone-mysql.yaml up启动nacos服务，build/conf/application.properties中设置的mysql配置就被覆盖了。是不是我哪里做得不对？

**Comment by paderlol** [comment]
……build/conf 只是构建docker镜像的源码部分而已…具体你可以参考readme
