### ISSUE TITLE
docker集群时,节点down

### ISSUE THREAD

**Issue by yfgcq** [nacos-group/nacos-docker#162]
1、主节点连接从节点异常  can not find peer: 10.201.23.2:8848
![20210128194404](https://user-images.githubusercontent.com/6744449/106135072-63174e00-61a2-11eb-9787-82722b765936.jpg)

2、从节点
![20210128194440](https://user-images.githubusercontent.com/6744449/106135100-6f9ba680-61a2-11eb-9feb-1e903d3e734b.jpg)

**Comment by yfgcq** [comment]
![20210128194404](https://user-images.githubusercontent.com/6744449/106134978-41b66200-61a2-11eb-8313-e6a93b789e63.jpg)
![20210128194440](https://user-images.githubusercontent.com/6744449/106135010-4bd86080-61a2-11eb-8681-1682f5de03db.jpg)

**Comment by paderlol** [comment]
两个ip能互通吗？然后配置cluster集群的ip要保证和selfip一致，否则也连不上，自己排查下raft日志

**Comment by yfgcq** [comment]
两个ip都是容器内部的，raft日志怎么查看勒？
`version: "3.5"
services:
  nacos1:
    image: nacos/nacos-server:latest
    container_name: nacos1
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      - ../env/nacos-ip.env
    restart: on-failure
    depends_on:
      - nacos_mysql
    networks:
      tsl-app:
        ipv4_address: 10.201.23.1

  nacos2:
    image: nacos/nacos-server:latest
    container_name: nacos2
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "8849:8848"
    env_file:
      - ../env/nacos-ip.env
    restart: always
    depends_on:
      - nacos_mysql
    networks:
      tsl-app:
        ipv4_address: 10.201.23.2

  nacos3:
    image: nacos/nacos-server:latest
    container_name: nacos3
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "8850:8848"
    env_file:
      - ../env/nacos-ip.env
    restart: always
    depends_on:
      - nacos_mysql
    networks:
      tsl-app:
        ipv4_address: 10.201.23.3

  nacos_mysql:
    container_name: nacos_mysql
    image: nacos/nacos-mysql:5.7
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3316:3306"
    networks:
      tsl-app:
        ipv4_address: 10.201.23.4
`
/////////////////////////////////////
`cat ../env/nacos-ip.env
#nacos dev env
NACOS_SERVERS=10.201.23.1:8848 10.201.23.2:8849 10.201.23.3:8850
MYSQL_SERVICE_HOST=10.201.23.4
MYSQL_SERVICE_DB_NAME=nacos_devtest
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=nacos
MYSQL_SERVICE_PASSWORD=nacos`

**Comment by paderlol** [comment]
你指定的内部容器ip，为什么要在配置NACOS_SERVERS的时候指定宿主机的端口？

**Comment by paderlol** [comment]
未回复,暂时关闭issue
