### ISSUE TITLE
nacos在集群里取到了docker网卡地址，不能获取正确的cluster server ip list

### ISSUE THREAD

**Issue by hongbinhsu** [nacos-group/nacos-docker#163]
部署Cluster模式时使用的默认配置，而默认提供的参数列表不能覆盖容器编排环境；确定提交的代码是本地跑过的？

**Comment by paderlol** [comment]
你配置的cluster地址，和读取那个地址是两个操作，每个节点会去验证本机地址符合当前的cluster里面某一个地址，确定自己的当前节点，你如果配置的是外网地址你需要自己通过NACOS_SERVER_IP去确定，我的例子里面已经写了两种，请提问题就提问题，也欢迎指正，请不要带着情绪去社区发问题，谢谢

**Comment by hongbinhsu** [comment]
> 你配置的cluster地址，和读取那个地址是两个操作，每个节点会去验证本机地址符合当前的cluster里面某一个地址，确定自己的当前节点，你如果配置的是外网地址你需要自己通过NACOS_SERVER_IP去确定，我的例子里面已经写了两种，请提问题就提问题，也欢迎指正，请不要带着情绪去社区发问题，谢谢

先初始化数据库，后通过IP的方式，已成功。
NACOS_SERVERS=ip1:8848 ip2:8848
NACOS_SERVER_IP=ip1    // ip2 使用对应宿主机内网IP
NACOS_SERVER_PORT=8848
MYSQL_SERVICE_HOST=mysql
MYSQL_SERVICE_DB_NAME=nacos_devtest
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=nacos
MYSQL_SERVICE_PASSWORD=nacos

**Comment by paderlol** [comment]
好的
