### ISSUE TITLE
docker做了nacos集群，节点也都上线了，发现2个问题，请教一下

### ISSUE THREAD

**Issue by fly7632785** [nacos-group/nacos-docker#164]
先上截图
![image](https://user-images.githubusercontent.com/10276266/108807952-7e7a4b00-75e0-11eb-8bfe-db25ede79d9c.png)

![image](https://user-images.githubusercontent.com/10276266/108808326-5a6b3980-75e1-11eb-96ac-96c37c469ceb.png)

第一个问题是，3台机子上部署了nacos，形成了集群，然后做了nginx的负载。发现服务注册了之后，只有某一台的控制台的服务列表界面是有服务的，其他两台没有，请问这样是正常的吗？（个人觉得是不是 3台服务列表都应该是同步的呢？）

第二个问题是，微服务集群都注册了之后，发现，有某个别实例，一直在不断的 健康 不健康 或者 实例数在2个和3个之间来回切换，刷新就会看到不停的在变，看了实例的日志也没有异常。请问有什么办法排查一下问题的呢？

谢谢

**Comment by paderlol** [comment]
选主有异常，看下raft的日志去排查下

**Comment by fly7632785** [comment]
请问第一个问题 可以 赐教一下吗

**Comment by fly7632785** [comment]
请问第一个问题 可以 赐教一下吗

**Comment by paderlol** [comment]
都是一个问题

**Comment by fly7632785** [comment]
从naming-server来看 日志 貌似正常

![image](https://user-images.githubusercontent.com/10276266/108808875-95ba3800-75e2-11eb-88d7-a396074d7eaa.png)

**Comment by fly7632785** [comment]
可否 加q 帮助一下 谢谢  522648467

**Comment by fly7632785** [comment]
alipay-jraft.log
![image](https://user-images.githubusercontent.com/10276266/108810030-22fe8c00-75e5-11eb-881d-e4f5e9bc4dc3.png)

报错提示 不能连接到 第二台机子的7848端口，3台机子防火墙都是关闭的

**Comment by paderlol** [comment]
第一你docker有没有把7848端口放出去，第二你日志里面显示的是在调用nacos1这种内部地址

**Comment by fly7632785** [comment]
你好  解决了 我直接--net=host  谢谢

**Comment by fly7632785** [comment]
😁
