### ISSUE TITLE
nacos单机模式注册失败，获取服务列表失败，错误码500

### ISSUE THREAD

**Issue by yinlijun2004** [nacos-group/nacos-docker#168]
nacos绑定外部8001端口
`version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    env_file:
      - ./.env
    volumes:
      - ${NACOS_LOG_DIR}:/home/nacos/logs
      - ${NACOS_PROPER_FILE}:/home/nacos/init.d/custom.properties
    ports:
      - "8001:8848"
    restart: on-failure 

networks:
  default:
    external:
     name: vibrator
`
.env里是mysql配置，mysql容器是5.7版本：
`PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=mysql
MYSQL_SERVICE_DB_NAME=vibrator_nacos
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=root
MYSQL_SERVICE_PASSWORD=123456

NACOS_LOG_DIR=/home/ubuntu/chaindata/docker/nacos/logs
NACOS_PROPER_FILE=/home/ubuntu/chaindata/docker/nacos/custom.properties
`

nacos管理页面可以访问，容器间可以ping通。
`root@iZ8vba75c22e0e8ypb4d69Z:/vibrator/nacos# docker exec -it vibrator-server-system /bin/bash
root@fed78e71a3b9:/# ping 172.30.0.8
PING 172.30.0.8 (172.30.0.8) 56(84) bytes of data.
64 bytes from 172.30.0.8: icmp_seq=1 ttl=64 time=0.077 ms
64 bytes from 172.30.0.8: icmp_seq=2 ttl=64 time=0.049 ms
64 bytes from 172.30.0.8: icmp_seq=3 ttl=64 time=0.045 ms`

但是注册报错信息，好像所有接口都报错：
`vibrator-server-system         | 2021-03-19 15:41:18 ERROR [Vibrator-Server-System,37d99d5c47b2d1a8,37d99d5c47b2d1a8,false] http-nio-8201-exec-1 com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient get service name from nacos server fail,
vibrator-server-system         | java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([nacos:8001]) tried: failed to req API:nacos:8001/nacos/v1/ns/service/list. code:500 msg: java.net.ConnectException: Connection refused (Connection refused)
vibrator-server-system         | 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467)
vibrator-server-system         | 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:433)
vibrator-server-system         | 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:379)
vibrator-server-system         | 	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:361)
vibrator-server-system         | 	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:458)
vibrator-server-system         | 	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:447)
vibrator-server-system         | 	at com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient.getServices(NacosDiscoveryClient.java:113)
vibrator-server-system         | 	at org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient.getServices(CompositeDiscoveryClient.java:67)
vibrator-server-system         | 	at org.springframework.cloud.client.discovery.health.DiscoveryClientHealthIndicator.health(DiscoveryClientHealthIndicator.java:69)
vibrator-server-system         | 	at org.springframework.cloud.client.discovery.health.DiscoveryCompositeHealthContributor.lambda$asHealthIndicator$0(DiscoveryCompositeHealthContributor.java:77)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:95)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:43)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:108)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:119)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:105)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:119)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:105)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:83)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:70)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:81)
vibrator-server-system         | 	at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:70)
vibrator-server-system         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
vibrator-server-system         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
vibrator-server-system         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
vibrator-server-system         | 	at java.lang.reflect.Method.invoke(Method.java:498)
vibrator-server-system         | 	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:279)
vibrator-server-system         | 	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:77)
vibrator-server-system         | 	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
vibrator-server-system         | 	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter.handle(AbstractWebMvcEndpointHandlerMapping.java:305)
vibrator-server-system         | 	at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(AbstractWebMvcEndpointHandlerMapping.java:388)
vibrator-server-system         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
vibrator-server-system         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
vibrator-server-system         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
`
请问是啥原因

**Comment by paderlol** [comment]
自己的数据库需要初始化脚本

**Comment by yinlijun2004** [comment]
> 自己的数据库需要初始化脚本

是有初始化的，执行过nacos_mysql.sql。
容器里也有对应的表。

`mysql> use vibrator_nacos;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+--------------------------+
| Tables_in_vibrator_nacos |
+--------------------------+
| config_info              |
| config_info_aggr         |
| config_info_beta         |
| config_info_tag          |
| config_tags_relation     |
| group_capacity           |
| his_config_info          |
| permissions              |
| roles                    |
| tenant_capacity          |
| tenant_info              |
| users                    |
+--------------------------+
12 rows in set (0.00 sec)
`

**Comment by paderlol** [comment]
你请求内部容器用的宿主机端口？naco: 8001？

**Comment by paderlol** [comment]
你看错误日志里面都告诉你refused了

**Comment by yinlijun2004** [comment]
分别属于不同的容器，容器vibrator-server-system访问容器nacos，域名可以ping通。
`root@iZ8vba75c22e0e8ypb4d69Z:/vibrator/vibrator-cloud# docker exec -it  vibrator-server-system /bin/bash
root@fed78e71a3b9:/# **ping nacos**
PING nacos (172.30.0.8) 56(84) bytes of data.
64 bytes from nacos.vibrator (172.30.0.8): icmp_seq=1 ttl=64 time=0.046 ms
64 bytes from nacos.vibrator (172.30.0.8): icmp_seq=2 ttl=64 time=0.040 ms
64 bytes from nacos.vibrator (172.30.0.8): icmp_seq=3 ttl=64 time=0.037 ms
^C
--- nacos ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2026ms
rtt min/avg/max/mdev = 0.037/0.041/0.046/0.003 ms
`

属于同一个网络vibrator:

root@iZ8vba75c22e0e8ypb4d69Z:/vibrator/vibrator-cloud# docker network inspect vibrator;
[
    {
        "Name": "vibrator",
        "Id": "42d1f1be55d736d9f0ed5ed8f15f637aec723686297f2177fceb2516ae85292c",
        "Created": "2021-03-19T18:45:04.206854425+08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.30.0.0/16",
                    "Gateway": "172.30.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "0549ecef0d9fcc78fd37b40d95e726f9b85e15194f4c915143c4d57563e8ecc9": {
                "Name": "nacos",
                "EndpointID": "6394fe23bdfa2339d315153bbd947de1cead7c4d7459a8b14904e655b07396a8",
                "MacAddress": "02:42:ac:1e:00:08",
                "IPv4Address": "172.30.0.8/16",
                "IPv6Address": ""
            },
            "ce28c458a254775017c1644d04500259252a5b94b63361757c531995b3eb1523": {
                "Name": "mysql",
                "EndpointID": "b4e4858d08abdf128a85ccfe75b5c23dd42d5aebf6aae4f28f37747aa7b6a231",
                "MacAddress": "02:42:ac:1e:00:04",
                "IPv4Address": "172.30.0.4/16",
                "IPv6Address": ""
            },
            "fed78e71a3b9c0c468407180c6232bbe639a2c562b245ab379c753df237c40b7": {
                "Name": "vibrator-server-system",
                "EndpointID": "7771ee82bda11e1964f2f7ecbe2991f712461530441ff9ce99cec0efe54e9dac",
                "MacAddress": "02:42:ac:1e:00:09",
                "IPv4Address": "172.30.0.9/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]

**Comment by paderlol** [comment]
你ping的通也不应该用8001啊，你应该用内部端口8848啊，你用个宿主机的端口，然后地址又用的nacos

**Comment by yinlijun2004** [comment]
谢谢，就是端口的问题，忘记关了
