### ISSUE TITLE
3台物理机 Docker方式 部署Cluster，每台一个Docker容器，但在Web上能看到4个节点

### ISSUE THREAD

**Issue by Interesting993** [nacos-group/nacos-docker#169]
请教一下。用3台物理机，部署Docker方式的Cluster，会在前台页面上看到4个节点，其中一个是Docker容器自己。这个能够关闭么？ 目前服务连接注册中心时会提示400，暂时不确定是不是和这个有关系

**Comment by paderlol** [comment]
Nacos选主没成功，你要确保配置的节点地址和节点本身的host或者ip能对应上，Nacos需要确保自己的每个节点ip一致，比如你配置的192.168.1.1是nacos1.那么你的nacos 内部也要有这个地址

**Comment by Interesting993** [comment]
假设我现在有3台物理机，IP是 1.1.1.2 1.1.1.3 1.1.1.4   我配置的是NACOS_SERVERS= 1.1.1.2:8848 1.1.1.3:8848 1.1.1.4:8848。在启动完成后，在前台的集群管理节点列表里能看到4个节点 除了上述3个外，额外还有一个172.16.0.21:8848。 这个172的地址是Docker容器自己的地址。并且3台的Docker容器都是这个地址。这种情况需要怎么调整呢？ 节点状态都是UP，并且每次Leader都是172那个IP。

**Comment by paderlol** [comment]
为每一台都指定对应地址selfip ，配置NACOS_SERVER_IP，比如第一台节点是1.1.1.2那就配置这个地址就行了

**Comment by Interesting993** [comment]
加上之后就可以了。谢谢
