### ISSUE TITLE
nacos集群模式，每个节点必须连接同一个mysql么？

### ISSUE THREAD

**Issue by wy82623** [nacos-group/nacos-docker#17]
nacos集群之间的数据同步机制是什么呢？
是依赖每个节点间的数据通信？还是依赖配置的同一个msql数据库呢？
如果每个节点连接的mysql数据库不是同一个可以么？

**Comment by paderlol** [comment]
nacos集群之间的同步机制 从配置来讲是依赖mysql主从数据库,从注册中心来讲依赖的raft算法保持,与数据库无关。

**Comment by wy82623** [comment]
> nacos集群之间的同步机制 从配置来讲是依赖mysql主从数据库,从注册中心来讲依赖的raft算法保持,与数据库无关。

就是说 
作为配置中心，是依赖数据库
作为注册中心，是依赖raft算法
主要是看用nacos来做什么了，是吧

**Comment by paderlol** [comment]
可以这么理解,但是目前配置中心和注册中心,并没有做分离,所以如果不配置数据库也还是无法启动的
