### ISSUE TITLE
nacos/nacos-mysql:5.7 无法更改时区

### ISSUE THREAD

**Issue by Dragonphy** [nacos-group/nacos-docker#170]
在`env/mysql.env` 设置时区`TZ=Asia/Shanghai`，无法生效，且运行docker-compose后，有如下异常日志：
```txt
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
```
改用官方mysql镜像，运行docker-compose后，无任何mysql异常日志输出

**建议更换官方mysql镜像**

**Comment by paderlol** [comment]
我们那个mysql镜像就是做个例子，因为用什么数据库镜像是你们根据自己公司情况而已
