### ISSUE TITLE
2.0 集群节点列表信息有个问题想请教一下

### ISSUE THREAD

**Issue by lovemianhuatang** [nacos-group/nacos-docker#175]
请问这个mate信息正常吗？
我是3台电脑，各有一个nacos服务。启动方式是使用docker stack deploy.

三个节点的naming_persistent_service 的 leader都是nacos1:7848

三个节点的其他mate 的 leader都是nacos2:7848

`{
    "lastRefreshTime": 1617892880057,
    "raftMetaData": {
        "metaDataMap": {
            "naming_instance_metadata": {
                "leader": "nacos2:7848",
                "raftGroupMember": [
                    "nacos3:7848",
                    "nacos1:7848",
                    "nacos2:7848"
                ],
                "term": 1
            },
            "naming_persistent_service": {
                "leader": "nacos1:7848",
                "raftGroupMember": [
                    "nacos3:7848",
                    "nacos1:7848",
                    "nacos2:7848"
                ],
                "term": 1
            },
            "naming_persistent_service_v2": {
                "leader": "nacos2:7848",
                "raftGroupMember": [
                    "nacos3:7848",
                    "nacos1:7848",
                    "nacos2:7848"
                ],
                "term": 1
            },
            "naming_service_metadata": {
                "leader": "nacos2:7848",
                "raftGroupMember": [
                    "nacos3:7848",
                    "nacos1:7848",
                    "nacos2:7848"
                ],
                "term": 1
            }
        }
    },
    "raftPort": "7848",
    "readyToUpgrade": true,
    "version": "2.0.0"
}`

**Comment by paderlol** [comment]
这个应该不正常，建议提问到Nacos社区问下

**Comment by lovemianhuatang** [comment]
我刚刚提问了，回复是正常的。
[https://github.com/alibaba/nacos/issues/5315](url)
