### ISSUE TITLE
2.0.1 版本连不上 mysql，报错 Could not create connection to database server

### ISSUE THREAD

**Issue by F91** [nacos-group/nacos-docker#182]
docker-compose -f standalone-mysql-8.yaml up -d
docker-compose -f standalone-mysql-5.7.yaml up -d
都报同样的错误

![image](https://user-images.githubusercontent.com/3523043/117247279-8f60fb80-ae70-11eb-9fac-9b94082ad229.png)

版本改回 2.0.0-bugfix 后，可以正常使用。

**Comment by paderlol** [comment]
因为升级了需要关闭ssl，可以自己设置下参数

**Comment by tzy1106** [comment]
nacos-docker/build/conf/application.properties
11、12行是不是也得添加
db.url.0=jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME}?${MYSQL_SERVICE_DB_PARAM:characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true}
db.url.1=jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME}?${MYSQL_SERVICE_DB_PARAM:characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true}

**Comment by paderlol** [comment]
配置环境变量就行了，不用管这里，你看我的提交吧

**Comment by F91** [comment]
试了下最新的提交，似乎还是同样的问题，手动关了 mysql 的 ssl 也不行。

![image](https://user-images.githubusercontent.com/3523043/117258432-8fb4c300-ae7f-11eb-8ae2-693cd30b554b.png)

还有个问题是，最新的提交里面，useSSL 前面有两个 "&&"，确定要两个吗？我试了下改成 1 个也不行，都是报 Could not create connection to database server

**Comment by paderlol** [comment]
需要把原来的挂载卷清除掉，我这边本地是可以的

**Comment by paderlol** [comment]
还有一种原因是数据库第一次启动比nacos要慢导致连不上，这种启动第二次或者自己写脚本等待数据库启动完成

**Comment by F91** [comment]
应该是数据库启动慢的原因，我试了下重启 nacos 容器就好了
