### ISSUE TITLE
nacos 执行编排命令不成功,报错[Note] Bad handshake,原因mysql的ssl没有关闭

### ISSUE THREAD

**Issue by 17097201102** [nacos-group/nacos-docker#184]
#虚拟机内部命令

#---------------------------------------问题产生步骤-----------------------------------------------
#创建自定义目录
mkdir /usr/local/nacos
#切换到自定义目录
cd /usr/local/nacos
#开始clone,拉取指定分支就行了
git clone https://github.com/nacos-group/nacos-docker.git
# 进入编排路径
cd /usr/local/nacos/nacos-docker/example

# 执行编排命令(需要关闭数据库的ssl)
docker-compose -f /usr/local/nacos/nacos-docker/example/cluster-hostname.yaml up

#控制台报错  mysql  [Note] Bad handshake
# 不能编排成功!!!!!!!!!!
#---------------------------------------解决方法-----------------------------------------------
原因mysql的ssl开启了,需要关闭
 docker exec -it mysql /bin/bash

cd /etc/mysql/conf.d
 vim my.cnf
#添加一行,关闭ssl
skip_ssl

#重启mysql
root@67db1f788bb4:/etc/mysql/conf.d# service mysql stop
..[root@localhost ~]# docker start mysql
mysql
root@67db1f788bb4:/# service mysql status
[info] MySQL Community Server 5.7.26 is running.

root@67db1f788bb4:/# cd /etc/mysql/conf.d

#登录mysql看看ssl的关闭情况
root@67db1f788bb4:/etc/mysql/conf.d# mysql -u nacos -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.26 MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

# 已经关闭了,就可以用了

mysql>  show variables like '%ssl%';
+---------------+----------+
| Variable_name | Value    |
+---------------+----------+
| have_openssl  | DISABLED |
| have_ssl      | DISABLED |
| ssl_ca        |          |
| ssl_capath    |          |
| ssl_cert      |          |
| ssl_cipher    |          |
| ssl_crl       |          |
| ssl_crlpath   |          |
| ssl_key       |          |
+---------------+----------+
9 rows in set (0.01 sec)

##启动nacos集群
docker-compose -f /usr/local/nacos/nacos-docker/example/cluster-hostname.yaml start

**Comment by paderlol** [comment]
直接配置数据库连接参数就行了，不需要进入容器更改，参考standalone MySQL 5.7

**Comment by hdfg159** [comment]
我也是，哈哈哈
