### ISSUE TITLE
8848服务查看不到集群列表

### ISSUE THREAD

**Issue by lhy507613824** [nacos-group/nacos-docker#186]
个人环境: VMware虚拟机内安装的docker; 虚拟机内访问8848;8849;8850都能正常看到集群列表。但是本地机器访问8848提示:no such api:GET:/nacos/v1/ns/operator/cluster/states   ;  本地访问8849,8850没有问题

**Comment by paderlol** [comment]
看看自己的虚拟机网络和和宿主机网络吧，这个问题应该跟docker或者nacos本身没什么关系

**Comment by lhy507613824** [comment]
> 看看自己的虚拟机网络和和宿主机网络吧，这个问题应该跟docker或者nacos本身没什么关系

VMware的网络连接是NAT模式,也就是说宿主机与虚拟机不是同一网段,改成桥接模式后(宿主机与虚拟机同一网段)后没有问题了。不过我不解的是,如果是因为是不同的网段造成了这个问题,那为什么8849与8850服务没问题只有8848有问题呢?

**Comment by paderlol** [comment]
不只是8848 你要看下9848端口是不是出问题了
