### ISSUE TITLE
升级到nacos/nacos-server:2.0.1  再custom.properties配置数据库连接信息，运行失效

### ISSUE THREAD

**Issue by maiqiumaker** [nacos-group/nacos-docker#188]
在旧版本nacos/nacos-server:1.4.2中  再custom.properties配置数据库连接信息，运行正常
升级到nacos/nacos-server:2.0.1  再custom.properties配置数据库连接信息，运行失效

**Comment by paderlol** [comment]
2.0.1 因为内部加载application.properties的顺序高于spring boot默认了，所以现在custom是在默认以后了，现在需要自定义就需要自己挂载application文件到宿主机了

**Comment by maiqiumaker** [comment]
了解了  谢谢

**Comment by fat8701** [comment]
踩到坑了...
