### ISSUE TITLE
怎么拉取不了镜像？

### ISSUE THREAD

**Issue by nodejsnewbie** [nacos-group/nacos-docker#192]
mac上，昨天今天都这样，翻墙都可以看油管，应该不是网络问题
docker-compose -f example/standalone-mysql-5.7.yaml up

Pulling nacos (nacos/nacos-server:2.0.2)...
ERROR: manifest for nacos/nacos-server:2.0.2 not found: manifest unknown: manifest unknown

**Comment by paderlol** [comment]
不好意思，忘了打tag了，目前2.0.2在latest上面，tag正在打
