### ISSUE TITLE
容器停止很慢, 且停止命令不安全

### ISSUE THREAD

**Issue by virnet** [nacos-group/nacos-docker#194]
![image](https://user-images.githubusercontent.com/29397860/123735225-6b022800-d8d1-11eb-8417-2397b5edb059.png)

原因: 
**在docker/k8s层面**，容器在停止的时候，会先发送kill信号给主进程(容器内pid=1的进程)。然后宽限期到了如果没有停止，会发送SIGKILL信号, SIGKILL信号是不优雅/不安全的的做法，会强制终止进程。比如可能程序内希望在关闭之前处理处理一些事物，但SIGKILL信号会让程序无法捕获，不会等待程序完成这些关闭前的优雅动作。
参考: https://docs.docker.com/engine/reference/commandline/stop/#extended-description
> The main process inside the container will receive SIGTERM, and after a grace period, SIGKILL. The first signal can be changed with the STOPSIGNAL instruction in the container’s Dockerfile, or the --stop-signal option to docker run.

**在Nacos服务层面**  nacos容器的启动脚本中，启动nacos主服务的命令是这样的:
https://github.com/nacos-group/nacos-docker/blob/22741e89fe13d105402d04404d54d2f3c761699c/build/bin/docker-startup.sh#L107
这会导致从启动脚本派生一个守护进程, 可能因为docker自身的原因，启动脚本会忽略这个TERM信号。而派生的进程也捕捉不到TERM信号。于是正常的KILL信号就无法工作，容器会等到宽限期后，发送SIGKILL信号给容器内的全部进程。
建议
将nohup 改成exec, 并且去掉启动日志的重定向，我个人觉得，把启动日志输出到容器的控制台是一个比较好的做法

一个题外问题, 这一行看起来没什么用，建议删除掉
https://github.com/nacos-group/nacos-docker/blob/22741e89fe13d105402d04404d54d2f3c761699c/build/bin/docker-startup.sh#L106

**Comment by paderlol** [comment]
好的，我下午抽时间看看

**Comment by paderlol** [comment]
Fixed
