### ISSUE TITLE
最近一次更新后，镜像无法正常使用

### ISSUE THREAD

**Issue by Simon-Wong-hjz** [nacos-group/nacos-docker#195]
今天下午尝试部署nacos到虚拟机docker，拉取到的镜像创建时间为2 hours ago，部署后nacos-server容器无限重启，日志显示docker-startup.sh语法报错，其他存有7 days ago镜像的则可以成功部署。
报错信息如下：
![image](https://user-images.githubusercontent.com/81307725/123776716-204cd400-d902-11eb-801d-9bb23032e6ae.png)

**Comment by paderlol** [comment]
好的。我看下

**Comment by hala21** [comment]
bin/docker-startup.sh 83行f-->fi 应该就可以了

**Comment by paderlol** [comment]
是楼上说的这个问题，不小心删除了fi里面的i导致的，我已经验证，重新push了

**Comment by Simon-Wong-hjz** [comment]
> 是楼上说的这个问题，不小心删除了fi里面的i导致的，我已经验证，重新push了

了解了，应该是刚才我修改这个文件的时候没有重新导入镜像所以不成功，感谢
