### ISSUE TITLE
建议在文档中写一下，要初始化数据库

### ISSUE THREAD

**Issue by WuHuaJi0** [nacos-group/nacos-docker#197]
使用单机-MySQL模式，没用example/standalone-mysql-5.7.yaml  中指定的数据库：nacos-mysql:5.7， 而是自己拉了一个MySQL5.7的镜像。

反复调整了各个配置，都会报错 No DataSource set。

后来我使用 nacos-mysql:5.7，居然能跑起来，又经过反复对比试验，发现 nacos-mysql:5.7 多了一些数据库。但接下来，我想查看 nacos-mysql:5.7 是如何构建出来的，在docker hub 上也没看到构建的信息（https://hub.docker.com/r/nacos/nacos-mysql）

在这个nacos-docker仓库下，查看build文件夹的信息，也没看出来 nacos-mysql:5.7 是如何构建出来的。

直到搜索了一下 issue，发现好几个人反馈了这个问题，得到的回答是：要初始化数据库。

但这个信息显然我没有看到过，如果不是看几个issue里面的信息，也不知道去哪找初始化sql脚本。

我主要看了官网的文档，https://nacos.io/zh-cn/docs/quick-start-docker.html ，所以是我漏看了么？ 如果不是还是注明一下比较好，有感于一晚上终于能跑起来了...

**Comment by paderlol** [comment]
好的 我会在Nacos Docker Readme 里面添加这个注意事项, 但是这个如果你用过Nacos 非docker版本 你应该知道是需要自己初始化数据库的,这是Nacos本身机制决定的,并不是docker决定的,我做的例子为了方便才自己重新定制了镜像

**Comment by WuHuaJi0** [comment]
> 好的 我会在Nacos Docker Readme 里面添加这个注意事项, 但是这个如果你用过Nacos 非docker版本 你应该知道是需要自己初始化数据库的,这是Nacos本身机制决定的,并不是docker决定的,我做的例子为了方便才自己重新定制了镜像

是的，我对nacos不是很熟悉，但是也能隐约猜到需要初始化数据。
不过这里引用了 nacos-server 和 nacos-mysql 两个镜像，我会潜意识以为是不是初始化数据库的操作在 nacos-server 里面做了（做了判断，如果找不到数据库就初始化），知道反复对比才发现初始化是在 nacos-mysql 里面做的 ：）


好的，那我关闭issue了 ：）
