### ISSUE TITLE
请问nacos/nacos-mysql:5.7的Dockerfile哪里能找到？

### ISSUE THREAD

**Issue by yusiwen** [nacos-group/nacos-docker#204]
我打算打个arm64的镜像，想看看这个nacos/nacos-mysql:5.7加入了哪些配置文件

谢谢啦

**Comment by paderlol** [comment]
就只是包装了下加载初始化脚本，所以没有开源，可以自行拿官方镜像自己包装

**Comment by paderlol** [comment]
我说的是Mysql官方镜像

**Comment by yusiwen** [comment]
@paderlol 
OK, 我理解是把schema脚本放到`/docker-entrypoint-initdb.d`目录下，是么？

**Comment by paderlol** [comment]
嗯

**Comment by yusiwen** [comment]
OK， 谢谢  👍 
Closing issue right now
