### ISSUE TITLE
nacos-docker 无法关闭控制台登录功能

### ISSUE THREAD

**Issue by shixitong** [nacos-group/nacos-docker#207]
配置如下
spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=/**
再次访问还是会跳转到登录页面
http://ip:8848/nacos/index.html

**Comment by shixitong** [comment]
版本是1.4.1

**Comment by paderlol** [comment]
要替换掉application.properties才能进行关闭
