### ISSUE TITLE
在 README 出现的描述性问题误导很多初学者

### ISSUE THREAD

**Issue by inernoro** [nacos-group/nacos-docker#214]
url : https://hub.docker.com/r/nacos/nacos-server
Service registration

curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'

这里使用了PUT，很多初学者在第一次运行命令行时如果都能出错，并且该错误并不容易查找，虽然可以参照restful原则
从此项证明了两点，READER 里的代码从未有人员自行用命令重新检查过一次，虽然是小问题，凸显了对该项目的不认真。

对一个项目的喜好程度，往往都是从第一次是否点亮开始，原版代码执行都无法成功点亮，会让很多人丧失对该项目的兴趣转投其他开源项目。

**Comment by paderlol** [comment]
嗯，谢谢，这个确实是问题，因为后期确实我因为个人工作问题就没怎么维护文档了，前期刚编写的时候确实是这个命令，后面未更新文档了。
