### ISSUE TITLE
在m1上可以通过docker-compose启动nacos吗？

### ISSUE THREAD

**Issue by cksspk** [nacos-group/nacos-docker#219]
<img width="1682" alt="docker-nacos-fail" src="https://user-images.githubusercontent.com/37790595/138410626-705dfece-b9a8-4be7-a9d4-3bb74d02cc41.png">

我这样启动，失败了。是因为配置文件写错了，还是目前不支持呢？

**Comment by o-hat** [comment]
启动不了 不支持m1  用这个zhusaidong/nacos-server-m1:2.0.3

**Comment by paderlol** [comment]
Fixed #257

**Comment by xstoop** [comment]
@paderlol 使用新的镜像还是无法启动![image](https://user-images.githubusercontent.com/15136017/169199605-0d751ff5-ef11-4f46-b9e6-3068313b8316.png)

**Comment by jsonchou** [comment]
``` java
nacos-standalone-mysql  | 03:56:02.960 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
nacos-standalone-mysql  | com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: ErrCode:500, ErrMsg:Function not implemented
```
