### ISSUE TITLE
log4j 漏洞, Nacos没有风险

### ISSUE THREAD

**Issue by abadfox233** [nacos-group/nacos-docker#226]
如题

**Comment by paderlol** [comment]
Nacos没有使用log4j做日志框架，server一直使用的logback，另外客户端的日志框架是optional选项，所以不太明白你说的升级指什么？？

**Comment by abadfox233** [comment]
好吧~_~，我以为nacos会有影响

**Comment by pccai** [comment]
但是nacos包里面有这个文件：
![image](https://user-images.githubusercontent.com/2232794/146337863-5626c506-fa84-4ee6-b666-7df4e9600c5e.png)

**Comment by pccai** [comment]
低于2.15.0.RC2

**Comment by paderlol** [comment]
> 低于2.15.0.RC2，所以能从nacos-server.jar包里面移除吗？

出问题需要log4j-core这个包才是bug包 
![image](https://user-images.githubusercontent.com/7919984/146469743-75c1f8c6-0eb3-498f-b987-31dc4b76533b.png)

原文出处 https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot

Nacos目前也会去升级,但是这个并不会造成 0 day
