### ISSUE TITLE
nscos docker-compose服务端经常会接连不上问题.

### ISSUE THREAD

**Issue by 13539956066** [nacos-group/nacos-docker#23]
git clone https://github.com/nacos-group/nacos-docker.git
cd nacos-docker
执行
docker-compose -f example/cluster-hostname.yaml up 

![RTX截图未命名](https://user-images.githubusercontent.com/31001390/54110421-4fcb3000-441c-11e9-92b1-a9f946d51738.png)

# ==== 执行 up 时是否有默认配置文件需要修改的？　
#=== 日志 上传
[nacos1.zip](https://github.com/nacos-group/nacos-docker/files/2951365/nacos1.zip)

**Comment by paderlol** [comment]
日志里面是你数据库未连接成功

**Comment by 13539956066** [comment]
收到,应该是防火墙问题,数据库访问不到
