### ISSUE TITLE
nacos-docker启动失败

### ISSUE THREAD

**Issue by gouez** [nacos-group/nacos-docker#24]
启动docker的时候提示如下，导致docker启动失败 
bin/docker-startup.sh: line 95: /home/nacos/logs/start.out: Permission denied

**Comment by paderlol** [comment]
一般是宿主机文件目录没权限写。可以看你docker工程放哪的

**Comment by gouez** [comment]
我刚刚试了，把目录权限修改为777，还是提示这个错误 。宿主的目录是/root/nacos

**Comment by paderlol** [comment]
我这边测试了没有这个问题的？所以可能你要排查下你权限的问题，或者先把打印日志先关掉

**Comment by gouez** [comment]
我刚刚把目录映射先关了，发现能启动。估计是我宿主权限问题，我再试试看  谢谢

**Comment by paderlol** [comment]
嗯，好的

**Comment by gouez** [comment]
可以了，关闭centos的SELinux

**Comment by paderlol** [comment]
😁好的，那麻烦你close点这个issue了
