### ISSUE TITLE
集群版mysql报错.

### ISSUE THREAD

**Issue by ChaselCho** [nacos-group/nacos-docker#25]
![image](https://user-images.githubusercontent.com/39975272/54661417-01e9b280-4b15-11e9-8c34-5e390d624852.png)

**Comment by paderlol** [comment]
请删除mysql的卷以及容器 重新启动一次 这个错误是说你mysql已经有一个同样的mysqlId了

**Comment by ChaselCho** [comment]
![image](https://user-images.githubusercontent.com/39975272/54663559-9c012900-4b1c-11e9-867c-bdb26ea39fef.png)
删掉后报这个错

**Comment by ChaselCho** [comment]
部署成功了 但是连不上 会报 failed to req API:/nacos/v1/ns/instance after all servers([xxxx:8848]) tried

**Comment by paderlol** [comment]
最新版本吗？如果用的最新版本需要先去控制台注册服务，然后再启动客户端注册实例

**Comment by zhangsongyang** [comment]
![image](https://user-images.githubusercontent.com/4935857/56495404-38f22000-6528-11e9-8ac9-5e554a9e3426.png)
docker集群运行 启动不起来

**Comment by paderlol** [comment]
你这个是主从为连接成功@zhangsongyang

**Comment by nodejsnewbie** [comment]
我也是遇到类似问题，不过我的情况有点不同，看了start.out，一直都是 INFO Nacos is starting...
在powershell其他都正常，有异常的部分如下：
nacos3          | + export DEFAULT_SEARCH_LOCATIONS=classpath:/,classpath:/config/,file:./,file:./config/
nacos3          | + DEFAULT_SEARCH_LOCATIONS=classpath:/,classpath:/config/,file:./,file:./config/
nacos3          | + export CUSTOM_SEARCH_LOCATIONS=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/
nacos3          | + CUSTOM_SEARCH_LOCATIONS=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/
nacos3          | + export CUSTOM_SEARCH_NAMES=application,custom
nacos3          | + CUSTOM_SEARCH_NAMES=application,custom
nacos3          | + PLUGINS_DIR=/home/nacos/plugins/peer-finder
nacos3          | + [[ cluster == \s\t\a\n\d\a\l\o\n\e ]]
nacos3          | + JAVA_OPT=' -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m'
nacos3          | + [[ n == \y ]]
nacos3          | + JAVA_OPT=' -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof'
nacos3          | + JAVA_OPT=' -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof -XX:-UseLargePages'
nacos3          | + print_servers
nacos3          | + [[ ! -d /home/nacos/plugins/peer-finder ]]
nacos3          | + echo ''
nacos3          | + for server in '${NACOS_SERVERS}'
nacos3          | + echo nacos1:8848
nacos3          | + for server in '${NACOS_SERVERS}'
nacos3          | + echo nacos2:8848
nacos3          | + for server in '${NACOS_SERVERS}'
nacos3          | + echo nacos3:8848
nacos3          | + [[ all == \c\o\n\f\i\g ]]
nacos3          | + [[ all == \n\a\m\i\n\g ]]
nacos3          | + [[ ! -z '' ]]
nacos3          | + [[ ! -z '' ]]
nacos3          | + [[ ! -z '' ]]
nacos3          | + [[ ! -z '' ]]
nacos3          | + [[ hostname == \h\o\s\t\n\a\m\e ]]
nacos3          | + JAVA_OPT=' -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.preferHostnameOverIp=true'
nacos3          | ++ /usr/lib/jvm/java-1.8.0-openjdk/bin/java -version
nacos3          | ++ sed -E -n 's/.* version "([0-9]*).*$/\1/p'


内存不够吗？需要怎么处理？

**Comment by paderlol** [comment]
你这个没有报内存不够啊，也没有错误啊

**Comment by nodejsnewbie** [comment]
可是访问http://localhost:8848/nacos   ，chrome 显示
该网页无法正常运作 localhost 未发送任何数据。
ERR_EMPTY_RESPONSE
单机版derby数据库的没问题，mysql的也是显示该网页无法正常运作

**Comment by paderlol** [comment]
你看下nacos的日志，nacos.log

**Comment by nodejsnewbie** [comment]
INFO Nacos is starting...     三个文件都是

**Comment by paderlol** [comment]
你看下你本地盘，有日志文件，应该就在你启动yaml同级目录，cluster-log

**Comment by nodejsnewbie** [comment]
[cluster-logs.zip](https://github.com/nacos-group/nacos-docker/files/3504895/cluster-logs.zip)
麻烦帮看看

**Comment by zhairuihao** [comment]
![image](https://user-images.githubusercontent.com/18378213/67449630-60e44c80-f64d-11e9-9147-43621433333f.png)
 nacos2/start.out 里的内容

**Comment by paderlol** [comment]
数据库没启动成功
