### ISSUE TITLE
docker-compose启动服务，导致nacos容器关闭

### ISSUE THREAD

**Issue by lczsf** [nacos-group/nacos-docker#258]
nacos配置
  nacosserver:
    image: nacos/nacos-server:v2.0.4
    container_name: nacos-standalone
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
    volumes:
      - ./standalone-logs/:/Users/admin/docker_nacos/logs
      - ./init.d/custom.properties:/Users/admin/docker_nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      default:
        ipv4_address: 172.19.0.4

服务配置
  ams:
    restart: always
    build: ../../ams
    ports:
      - "8021:8021"
    depends_on:
      - gateway
    networks:
      default:
        ipv4_address: 172.19.0.6
先启动nacos正常，只要启动ams就会导致nacos down. ams是一个普通的服务。不用容器启动没有问题。

**Comment by paderlol** [comment]
检查下是否是你docker分配的内存不够，nacos要的内存比较大，并且custom properties已经声明移除了
