### ISSUE TITLE
v2.1.1无法部署

### ISSUE THREAD

**Issue by HantaoCai** [nacos-group/nacos-docker#284]
docker-compose -f example/standalone-mysql-8.yaml up -d

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/44667064/196937845-54f84211-faa1-435d-ab4a-57842b09276d.png">

换自己的数据库 换各种环境变量都不能部署

**Comment by nbbINjmw** [comment]
同问

**Comment by paderlol** [comment]
这种有几种情况,一种数据库并没有启动成功, 另外如果用自己的数据库需要自己初始化SQL脚本

**Comment by HantaoCai** [comment]
新版已经修了，可以启动。 同时需要新的docker-compose 支持tag
