### ISSUE TITLE
Make sure the database is up before starting Nacos

### ISSUE THREAD

**Issue by zhangt2333** [nacos-group/nacos-docker#286]
Hi, I've been using Nacos in my projects for two years, and the project helped me to quickly set up Nacos in mutiple environments. Thanks for your efforts to provide us a way to launch Nacos in just one step.

Currently, I have some feature requests (or suggestions) for this project based on my experiences.

I notice that [standalone-mysql-5.7.yaml](https://github.com/nacos-group/nacos-docker/blob/3736ce9a58/example/standalone-mysql-5.7.yaml) uses [`mysqladmin ping -h localhost`](https://github.com/nacos-group/nacos-docker/blob/3736ce9a58/example/standalone-mysql-5.7.yaml#L34-L38) as a health checking command and [`depends_on: mysql: condition: service_healthy`](https://github.com/nacos-group/nacos-docker/blob/3736ce9a58/example/standalone-mysql-5.7.yaml#L15-L17) as the precondition for Nacos container creation.

There are some potential issues (my actual experiences) as the following reasons:
1. `mysqladmin ping` will still return `0` if MySQL is running but not yet accepting connections. (It is very easy to reproduce, e.g., by having a large SQL initialization file in `/docker-entrypoint-initdb.d`)
2. Based on the first point I mentioned, Nacos will then fail to start and there will be a log `Caused by: java.lang.IllegalStateException: No DataSource set`.
3. From then on, Nacos donot attempt to reconnect MySQL, even if MySQL is be actually ready.

I have tried to do some workarounds (but failed) that would not require any changes on the Nacos image:
1. Uses `timeout 5s bash -c ':> /dev/tcp/localhost/3306' || exit 1` (according to [this](https://medium.com/bash-tips-and-tricks/part01-tcp-udp-request-with-a-native-bash-feature-and-without-curl-wget-9dcef59c30aa)) as a truly approach to MySQL health checking. 
2. The Nacos container was never created because it was waiting for the MySQL to be ready. Just when I thought it was going to wait for MySQL, the docker-compose error aborted.
```
ERROR: for nacos  Container "6f7a8a6d9434" is unhealthy.      # "6f7..." is the MySQL container
ERROR: Encountered errors while bringing up the project.
```

By the way, my docker version is `20.10.13` and docker-compose version is `1.29.2`.

----------------------

My suggested solutions:

1. To include a script in the Nacos image to poll a given host and port until it’s accepting TCP connections, e.g, [wait-for-it](https://github.com/vishnubob/wait-for-it) and [docker-compose-wait](https://github.com/ufoscout/docker-compose-wait) according to this [Docker Official Document](https://docs.docker.com/compose/startup-order/). As an example, if I use [docker-compose-wait](https://github.com/ufoscout/docker-compose-wait) in my Docker image, I just need to configure the environment variables `WAIT_HOSTS` to automatically wait for the appropriate service to be ready. (Nothing happens if there are no related environment variables.)
```yaml
  myApp:
    image: "myApp:latest"
    environment:
      WAIT_HOSTS: mysql:3306, redis:6379
```
2. If you think my first solution is too invasive, you could at least consider changing `mysqladmin ping -h localhost` to a truly approach to MySQL health checking, e.g., `timeout 5s bash -c ':> /dev/tcp/localhost/3306' || exit 1`. 

**Looking forward to hearing from you!** 

**And I would be pleased to submit a PR for this if you agree**.

Thanks!

**Comment by paderlol** [comment]
Thanks for the suggestions, but in my opinion, they are just some examples to give you a quick experience with Nacos, the production environment is not one that we need to pay attention to, because every company's production environment database or other components will be created in such a fragile way, so I prefer to keep it as it is now

**Comment by zhangt2333** [comment]
Thanks for your reply. I share your sentiments that this repo give developers a quick experience with Nacos. That's exactly what happened, so many projects in the open source community will use Docker-compose to provide a quick deployment approach for them.

If you prefer not to introduce an external script to check health of dependency so that Nacos could start normally, currently there is still a lack of retry/restart mechanism after a Nacos's failed launch.

That is, if the DB does not finish starting, the Nacos will not exit that `restart: on-failure` in [standalone-mysql-5.7.yaml](https://github.com/nacos-group/nacos-docker/blob/6f25e6f67e/example/standalone-mysql-5.7.yaml#L3-L19) will also not work. (Just run `docker run -di -e PREFER_HOST_MODE=hostname -e MODE=standalone -e SPRING_DATASOURCE_PLATFORM=mysql  nacos/nacos-server`, the container will not exit even though it has thrown `java.lang.IllegalStateException: No DataSource set`)

So, I also suggest the health checking for Nacos based on the endpoint (maybe `/nacos/actuator/health`?) in the [standalone-mysql-5.7.yaml](https://github.com/nacos-group/nacos-docker/blob/6f25e6f67e/example/standalone-mysql-5.7.yaml#L3-L19).

**Comment by zhangt2333** [comment]
@kamjin1996 Thank you for sharing your experience. I agree with you that this repo offer us a basic Docker Image for Nacos and we can custom one of our own to accommodate the needs of each individual.

It's been a long time since I started this issue. I already have the workaround for me to use dockerized Nacos.

I now share this as a less invasive solution for those who are struggling with this problem:

* In [./example/compose.yaml](https://github.com/SDUOJ/sduoj-deploy/blob/2c5ab43f90/example/pseudo-distributed-ip.yaml#L47-L65), you can rebuild Nacos on top of the official image:
```yaml
  nacos:
    build:
      context: ../build/nacos/2.1.2
    environment:
      WAIT_HOSTS: mysql:3306
```

* In [../build/nacos/2.1.2/Dockerfile](https://github.com/SDUOJ/sduoj-deploy/blob/2c5ab43f908b1c73bba38feb8af6814fc3f9435c/build/sduoj-nacos/2.1.2/Dockerfile), you can customize what you need:
```Dockerfile
FROM nacos/nacos-server:v2.1.2-slim

# download docker-compose-wait, it will automatically adapt to the platform
COPY --from=sduoj/docker-compose-wait:latest /wait /wait

ENTRYPOINT /wait && bin/docker-startup.sh
```
