### ISSUE TITLE
example/.env 文件 NACOS_VERSION的值少了个v

### ISSUE THREAD

**Issue by agzou** [nacos-group/nacos-docker#301]
~~NACOS_VERSION=2.1.2~~

 应该是 NACOS_VERSION=v2.1.2

**Comment by agzou** [comment]
[https://github.com/nacos-group/nacos-docker/blob/c404421e5ed44b976ef7b8be29c0facadbc3c810/example/.env](url)

**Comment by agzou** [comment]
https://github.com/nacos-group/nacos-docker/blob/c404421e5ed44b976ef7b8be29c0facadbc3c810/example/.env

**Comment by paderlol** [comment]
已修复
