### ISSUE TITLE
数据库初始化脚本链接失败

### ISSUE THREAD

**Issue by qq280948982** [nacos-group/nacos-docker#307]
文档中的注意事项中的最后一项：
“如果你使用自定义数据库, 第一次启动Nacos前需要手动初始化 [数据库脚本](https://github.com/alibaba/nacos/blob/develop/distribution/conf/nacos-mysql.sql) .”

上面的 数据库脚本 链接已失效，打开是404页面，在哪里可以找到？

**Comment by InGramViking** [comment]
https://github.com/alibaba/nacos/blob/master/distribution/conf/mysql-schema.sql

**Comment by paderlol** [comment]
感谢PR
