### ISSUE TITLE
执行docker-compose -f standalone-derby.yaml up -d错误

### ISSUE THREAD

**Issue by 1346735074** [nacos-group/nacos-docker#32]
Deploying 'Compose: example'...
/usr/local/bin/docker-compose -f /Volumes/CodeFile/GitHub/1346735074/elk-engine/nacos-docker/example/standalone-derby.yaml up -d
Creating grafana ... 
Creating nacos-standalone ... 
Creating nacos-standalone ... error
ERROR: for nacos-standalone  Cannot start service nacos: b'OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/Volumes/CodeFile/GitHub/1346735074/elk-engine/nacos-docker/example/init.d/custom.properties\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/d97d321c23636c83e535666513730021354014f92b1e10ae5e87cca70b4a52df/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/d97d321c23636c83e535666513730021354014f92b1e10ae5e87cca70b4a52df/merged/home/nacos/init.d/custom.properties\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'
Creating grafana          ... done
ERROR: for nacos  Cannot start service nacos: b'OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/Volumes/CodeFile/GitHub/1346735074/elk-engine/nacos-docker/example/init.d/custom.properties\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/d97d321c23636c83e535666513730021354014f92b1e10ae5e87cca70b4a52df/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/d97d321c23636c83e535666513730021354014f92b1e10ae5e87cca70b4a52df/merged/home/nacos/init.d/custom.properties\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'
ERROR: Encountered errors while bringing up the project.
Failed to deploy 'Compose: example': `docker-compose` process finished with exit code 1

**Comment by paderlol** [comment]
你是不是做了挂卷操作？

**Comment by 1346735074** [comment]
standalone-derby.yaml文件是在home文件下存放
在该目录下执行的

**Comment by 1346735074** [comment]
谢谢了  已经修复了  服务器只上传了standalone-derby.yaml文件  发现里面有引用其他文件

**Comment by paderlol** [comment]
恩 引用了环境变量文件 env目录下面

**Comment by paderlol** [comment]
解决了 就麻烦关闭下issue,谢谢哈
