### ISSUE TITLE
arm64内核centos7,docker-compose运行nacos2.1.1集群失败

### ISSUE THREAD

**Issue by baozhuming** [nacos-group/nacos-docker#322]
[nacos-hostname.txt](https://github.com/nacos-group/nacos-docker/files/10988344/nacos-hostname.txt)
[cluster-hostname.txt](https://github.com/nacos-group/nacos-docker/files/10988346/cluster-hostname.txt)
<img width="625" alt="截屏2023-03-16 16 22 17" src="https://user-images.githubusercontent.com/20451418/225557293-d79bded3-a626-455e-8294-d5bb90018434.png">
<img width="625" alt="截屏2023-03-16 16 21 31" src="https://user-images.githubusercontent.com/20451418/225557328-29af0a29-3a67-4e10-9286-611cf53c9cca.png">

**Comment by paderlol** [comment]
arm内核需要使用v2.1.1-slim
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/7919984/226587735-0500bfdd-037d-4eca-8e54-8a33433121d6.png">
