### ISSUE TITLE
版本不一致

### ISSUE THREAD

**Issue by duansheli** [nacos-group/nacos-docker#34]
所有版本的文件example/standalone-derby.yaml中
定义的nacos镜像版本是latest
0.7的0.9的都是这样

目前最新版本是1.0
如果下载一个0.7
https://github.com/nacos-group/nacos-docker/archive/0.7.0.tar.gz
则docker版的nacos依然是1.0的

**Comment by paderlol** [comment]
我不是太理解你的意思，你是说配置的镜像的版本，还是？

**Comment by duansheli** [comment]
@paderlol 镜像版本。   
https://github.com/nacos-group/nacos-docker/blob/b0531c105ce20c24ebd3f36705001b20112af203/example/standalone-derby.yaml#L4  
项目nacos-k8s中的也是没有指定具体版本。

**Comment by paderlol** [comment]
因为例子默认就是最新版本啊，如果你需要不同的版本自己把latest更改就行了，至于分支，是我每次针对不同版本的开发分支的。

**Comment by paderlol** [comment]
你去nacos下载具体版本，和docker镜像版本是没有任何关系的，docker镜像版本是根据镜像名称后面的tag来的
