### ISSUE TITLE
前置nginx反向代理到nacos的8848端口，无法代理

### ISSUE THREAD

**Issue by NicknameID** [nacos-group/nacos-docker#35]
用docker启动了一个nacos容器，映射到主机的8848端口。又起了一个nginx作为反向代理，把主机80端口代理到8848端口，但是代理失败，报502错误

**Comment by NicknameID** [comment]
问题已查清，是由于docker的网络模式的问题

**Comment by bombbb** [comment]
> 问题已查清，是由于docker的网络模式的问题

您成功的时候用的是什么网络 模式。

**Comment by miozus** [comment]
你反向代理的监听端口不应该是 8848 吧， 应该由其他端口（比如随便1111）转发 本地链接8848；否则你nginx端口占用要被挤下去。
