### ISSUE TITLE
仓库很大，建议精简

### ISSUE THREAD

**Issue by zgfh** [nacos-group/nacos-docker#36]
我看到master 分之其实就是几个配置文件，但下载半天,发现是第一个版本有一个jar造成的，rebase下？这样下载会快很多
![image](https://user-images.githubusercontent.com/11729624/58149847-2d188b80-7c97-11e9-9bfe-dec978d0c53e.png)

**Comment by paderlol** [comment]
好的，谢谢

**Comment by paderlol** [comment]
已经修复了

**Comment by zgfh** [comment]
👍

**Comment by shalk** [comment]
仓库还是很大，建议删除一下历史文件。删除之后122kb，删除之前45mb
```
git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch build/nacos/target/nacos-server.jar" HEAD
```

**Comment by paderlol** [comment]
> 仓库还是很大，建议删除一下历史文件。删除之后122kb，删除之前45mb
> 
> ```
> git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch build/nacos/target/nacos-server.jar" HEAD
> ```
> 
> 可以拷贝我已经改好的
> 
> https://github.com/shalk/nacos-docker

恩 谢谢提醒,已经处理过了,之前只处理了master
