### ISSUE TITLE
自定义的端口不生效

### ISSUE THREAD

**Issue by hy-2019** [nacos-group/nacos-docker#365]
我用的单机启动 在init.d/application.properties配置了新的端口 在单机启动的docker文件也配置了新的端口 启动还是8848

**Comment by WVenus** [comment]
指定端口请使用 NACOS_APPLICATION_PORT变量

**Comment by hy-2019** [comment]
好的。感谢你的解答，问题已经解决了


| |
黄毅
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月23日 10:10 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [nacos-group/nacos-docker] 自定义的端口不生效 (Issue #365) |

指定端口请使用 NACOS_APPLICATION_PORT变量

**Comment by WVenus** [comment]
@hy-2019 好的， 请关闭一下issue

**Comment by hy-2019** [comment]
好的
