### ISSUE TITLE
你好安装的nacos集群版本，prometheus没有数据

### ISSUE THREAD

**Issue by hskycloud** [nacos-group/nacos-docker#38]
![image](https://user-images.githubusercontent.com/29112690/59857296-3a668a00-93ab-11e9-89f7-040e3b8a4f95.png)

**Comment by hskycloud** [comment]
找到原因了，虚拟机的时间问题，不好意思！

**Comment by Lazy-F** [comment]
@hskycloud 你好..我遇到了同样的问题. 请教一下是怎么解决的呢..

**Comment by hskycloud** [comment]
我是docker容器的时间不对导致采集到的时间有问题所以不能展示。你可以启动的时候让容器同步服务器时间。

Do Our Best
得不到的永远在骚动，被偏爱的都有恃无恐！
