### ISSUE TITLE
无法连接到外部mysql, 启动时报错 IllegalStateException: No DataSource set

### ISSUE THREAD

**Issue by syrm-ll** [nacos-group/nacos-docker#383]
## 问题描述
我使用 docker compose 配置服务,  nacos 容器启动时无法连接到同网络下的 mysql 实例, 在启动后稍等片刻抛出 `IllegalStateException: No DataSource set`

 但诡异的是, 如果在外部手动访问 mysql 一次, nacos 容器就可以正常连接... ? 我不明白为什么

我创建了一个最小案例, 在 README.md 中提供了我的环境信息
 <https://github.com/syrm-test/feedback-20231129>

### 这个问题存在很久了, 类似问题列表
<https://github.com/nacos-group/nacos-docker/issues/354> 这个是我以前提交的, 当时使用 `docker run` 运行 同样无法连接, 始终未解决
<https://github.com/nacos-group/nacos-docker/issues/355> 这是个类似的问题, 我尝试了很多次 `service name` `container_name` 都可以用, 前提是先访问 mysql 一次

<https://github.com/nacos-group/nacos-docker/issues/362> 这位也提到需要单独连接一次 mysql, 原因未知

<https://github.com/nacos-group/nacos-docker/issues/280> 这个问题提到 可能和 `useSSL` 参数有关, 我没有尝试
<https://github.com/nacos-group/nacos-docker/issues/276> 这是个更早期的问题

### 另外
`SPRING_DATASOURCE_PLATFORM | 单机模式下支持MYSQL数据库 | mysql / 空 默认:空` 这个环境变量的解释对新用户很不友好
默认的空似乎使用的嵌入式数据库? 指定为 mysql 才会使用 `MYSQL_SERVICE_*` 相关的变量配置的外部mysql

在排查上面问题时 这个配置令人困惑, 很多次以为成功了, 结果配置文件根本没保存
也有些相关问题以为解决了, 其实没有配置这个变量

**Comment by slightlee** [comment]
基于你的代码 https://github.com/syrm-test/feedback-20231129  需要改动地方 
1、nacos 配置 添加 - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
2、mysql healthcheck 调整为  test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p111111"]  此处账号密码不想明文可从配置文件中获取 。之前健康检查ping只能判断mysql容器是否启动，但初始化数据是否插入完成判断不了  
也可参考 我写的脚本 [docker](https://github.com/slightlee/docker)

**Comment by slightlee** [comment]
> ## 问题描述
> 我使用 docker compose 配置服务, nacos 容器启动时无法连接到同网络下的 mysql 实例, 在启动后稍等片刻抛出 `IllegalStateException: No DataSource set`
> 
> 但诡异的是, 如果在外部手动访问 mysql 一次, nacos 容器就可以正常连接... ? 我不明白为什么
> 
> 我创建了一个最小案例, 在 README.md 中提供了我的环境信息 https://github.com/syrm-test/feedback-20231129
> 
> ### 这个问题存在很久了, 类似问题列表
> #354 这个是我以前提交的, 当时使用 `docker run` 运行 同样无法连接, 始终未解决 #355 这是个类似的问题, 我尝试了很多次 `service name` `container_name` 都可以用, 前提是先访问 mysql 一次
> 
> #362 这位也提到需要单独连接一次 mysql, 原因未知
> 
> #280 这个问题提到 可能和 `useSSL` 参数有关, 我没有尝试 #276 这是个更早期的问题
> 
> ### 另外
> `SPRING_DATASOURCE_PLATFORM | 单机模式下支持MYSQL数据库 | mysql / 空 默认:空` 这个环境变量的解释对新用户很不友好 默认的空似乎使用的嵌入式数据库? 指定为 mysql 才会使用 `MYSQL_SERVICE_*` 相关的变量配置的外部mysql
> 
> 在排查上面问题时 这个配置令人困惑, 很多次以为成功了, 结果配置文件根本没保存 也有些相关问题以为解决了, 其实没有配置这个变量

基于你的代码 https://github.com/syrm-test/feedback-20231129 需要改动地方
1、nacos 配置 添加 - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
2、mysql healthcheck 调整为 test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p111111"] 此处账号密码不想明文可从配置文件中获取 。之前健康检查ping只能判断mysql容器是否启动，但初始化数据是否插入完成判断不了
也可参考 我写的脚本 [docker](https://github.com/slightlee/docker)

**Comment by paderlol** [comment]
> ## 问题描述
> 我使用 docker compose 配置服务, nacos 容器启动时无法连接到同网络下的 mysql 实例, 在启动后稍等片刻抛出 `IllegalStateException: No DataSource set`
> 
> 但诡异的是, 如果在外部手动访问 mysql 一次, nacos 容器就可以正常连接... ? 我不明白为什么
> 
> 我创建了一个最小案例, 在 README.md 中提供了我的环境信息 https://github.com/syrm-test/feedback-20231129
> 
> ### 这个问题存在很久了, 类似问题列表
> #354 这个是我以前提交的, 当时使用 `docker run` 运行 同样无法连接, 始终未解决 #355 这是个类似的问题, 我尝试了很多次 `service name` `container_name` 都可以用, 前提是先访问 mysql 一次
> 
> #362 这位也提到需要单独连接一次 mysql, 原因未知
> 
> #280 这个问题提到 可能和 `useSSL` 参数有关, 我没有尝试 #276 这是个更早期的问题
> 
> ### 另外
> `SPRING_DATASOURCE_PLATFORM | 单机模式下支持MYSQL数据库 | mysql / 空 默认:空` 这个环境变量的解释对新用户很不友好 默认的空似乎使用的嵌入式数据库? 指定为 mysql 才会使用 `MYSQL_SERVICE_*` 相关的变量配置的外部mysql
> 
> 在排查上面问题时 这个配置令人困惑, 很多次以为成功了, 结果配置文件根本没保存 也有些相关问题以为解决了, 其实没有配置这个变量

另外这个问题应该提issue到nacos server吧 这个变量对于docker来讲只是单纯的包装而已

**Comment by syrm-ll** [comment]
@slightlee 感谢大佬, 我试了下确实没问题了
