### ISSUE TITLE
集群版nacos的内存占用怎么调整

### ISSUE THREAD

**Issue by xiejx618** [nacos-group/nacos-docker#41]
3个nacos实例+2个mysql实例+监控，总体来看占内存有点大,单是nacos就6G内存. 是否可以把内存配置抽成变量

当然不希望自己修改脚本重新打镜像。

**Comment by paderlol** [comment]
好的，我这边优化下

**Comment by xiejx618** [comment]
我以为将JAVA虚拟机参数由成一个变量，这样就很自由，但这样也基本达到目的。

**Comment by paderlol** [comment]
如果变成变量会有一些问题，因为可能要告诉用户默认是哪些，还需要考虑本身nacos对JVM的一些定义
