### ISSUE TITLE
nacos cluster模式由2.3.2升级到2.4.0报错

### ISSUE THREAD

**Issue by q164749** [nacos-group/nacos-docker#424]
由于2.4.0版本的 nacos 使用了 Alpine Linux 作为底层镜像，默认没有 bash 解释器，导致 cluster 模式的 nacos 启动时报错，plugin.sh 无法执行

bin/docker-startup.sh: line 26: bash: not found

![image](https://github.com/user-attachments/assets/98112331-ecf6-47cc-af27-2f32165a8592)

继而导致没有生成 cluster.conf ，然后服务启动就报错 

Caused by: java.net.UnknownHostException: jmenv.tbsite.net

**Comment by ygqygq2** [comment]
镜像都没有 bash，脚本用的 bash 启动

**Comment by paderlol** [comment]
已经修复了 https://github.com/nacos-group/nacos-docker/pull/425
很抱歉带来的不便
