### ISSUE TITLE
windows 10环境下用powershell执行，出错了

### ISSUE THREAD

**Issue by nodejsnewbie** [nacos-group/nacos-docker#47]
PS D:\repo\nacos-docker> docker-compose -f .\example\standalone-mysql.yaml up
Starting mysql-master ...
Starting mysql-master ... error

ERROR: for mysql-master  Cannot start service mysql-master: b"error while creating mount source path '/host_mnt/d/repo/nacos-docker/example/mysql-master': mkdir /host_mnt/d: file exists"

ERROR: for mysql-master  Cannot start service mysql-master: b"error while creating mount source path '/host_mnt/d/repo/nacos-docker/example/mysql-master': mkdir /host_mnt/d: file exists"
ERROR: Encountered errors while bringing up the project.

**Comment by paderlol** [comment]
这不是Nacos的错误，这个可能因为你自己容器启动时和你当前这个盘成为了共享卷导致的，这个问题是由于该容器生成时，与本地主机创建了共享目录D:（异常描述中得知），解决办法是：右键docker客户端，点击setting，将里面的共享盘取消，应用即可

**Comment by paderlol** [comment]
你可以看下docker官方的这个[issue](https://github.com/docker/for-win/issues/1560),这个issue是关于你这个问题的解答。
