### ISSUE TITLE
使用standalone-mysql.yaml无法访问nacos

### ISSUE THREAD

**Issue by nodejsnewbie** [nacos-group/nacos-docker#48]
命令：
docker-compose -f .\example\standalone-mysql.yaml up

[start.out.zip](https://github.com/nacos-group/nacos-docker/files/3507917/start.out.zip)

**Comment by paderlol** [comment]
你这是数据库没连接成功,你看下docker-compose的启动日志分析下

**Comment by SongJiaxin95** [comment]
我也遇到了这个问题，拉下来后没改动任何文件，standalone-mysql无法访问nacos

**Comment by dk-lockdown** [comment]
> 我也遇到了这个问题，拉下来后没改动任何文件，standalone-mysql无法访问nacos

nacos mysql slave的端口也应该是3306，我已经提了一个pr了

**Comment by jarod-jin** [comment]
nacos mysql slave的端口和master 应该是一样是3306的除非 这两个docker不是在一个内部网络中
