### ISSUE TITLE
docker部署nacos-server:1.1.3单机模式，配置写为 spring.datasource.platform="mysql" 报错，改成spring.datasource.platform=""就可以了。正文看报错截图 

### ISSUE THREAD

**Issue by chenxing0755** [nacos-group/nacos-docker#51]
docker 容器启动 通过挂载 /home/nacos/conf写配置参数 和 通过-e传入参数都试过了，都不行，nacos.log 报错日志见下面截图。最后把spring.datasource.platform=""就可以了

![16_47_06__08_23_2019](https://user-images.githubusercontent.com/45444321/63579905-3b43b400-c5c6-11e9-8240-81439bfdb6e6.JPG)

**Comment by yuweizhao2018** [comment]
你这样改了就还是连的nacos自带的nosql数据库了，我也遇到同样的问题，希望作者能帮忙解答一下

**Comment by paderlol** [comment]
我记得这个有参数的吧？我也有一个compose的例子专门写的单机带数据库的

**Comment by yuweizhao2018** [comment]
老哥你知道怎么配置吗？
![image](https://user-images.githubusercontent.com/20539173/68367785-6d01fb00-0171-11ea-8215-1ff6e75eddb7.png)

**Comment by paderlol** [comment]
https://github.com/nacos-group/nacos-docker/blob/master/example/standalone-mysql.yaml

**Comment by paderlol** [comment]
https://github.com/nacos-group/nacos-docker/blob/master/build/conf/application.properties 参考下这是docker容器里面的application配置写法，挂载的时候请自己复制一份出来，或者使用扩展配置文件

**Comment by yuweizhao2018** [comment]
![image](https://user-images.githubusercontent.com/20539173/68368651-7be9ad00-0173-11ea-8953-0509fb5ef50d.png)
依然没生效，还是连的自带的数据库

**Comment by paderlol** [comment]
你去掉双引号，然后确定自己的卷挂对了

**Comment by yuweizhao2018** [comment]
卷挂载对了，我将刚才那个配置去掉双引号放在了config目录，启动报错
![image](https://user-images.githubusercontent.com/20539173/68369112-80629580-0174-11ea-967a-55af4c2a5f30.png)

**Comment by paderlol** [comment]
你配置的localhost啊，这指的是容器的地址啊，你要配置具体的地址，如果你数据库在本机的宿主机，那就配置宿主机的地址，如果是外网就配置外网的地址

**Comment by yuweizhao2018** [comment]
可以了，老哥，多谢！

**Comment by wyg-0807** [comment]
> 可以了，老哥，多谢！

怎么弄得啊，始终是默认的数据库
