### ISSUE TITLE
建议改一下quick start

### ISSUE THREAD

**Issue by fatg1988** [nacos-group/nacos-docker#54]
quick start 步骤太长，里面那些prometheus、grafana没必要启动，用户来了只是为了尝试nacos。
直接一条docker命令启动，如果-e是默认的能省略更好。
docker run -d -p 8848:8848 -e "PREFER_HOST_MODE=hostname" -e "MODE=standalone" nacos/nacos-server

**Comment by paderlol** [comment]
ok
