### ISSUE TITLE
如何升级nacos-mysql-master和slave docker镜像到mysql 最新版本

### ISSUE THREAD

**Issue by NaziGanster** [nacos-group/nacos-docker#55]
如何升级nacos-mysql-master和slave docker镜像到mysql 最新版本

**Comment by paderlol** [comment]
这个是例子镜像，不用于生产…需要可以自己构建一个的

**Comment by NaziGanster** [comment]
nacos-mysql-master的dockerfile和里面需要的脚本在哪能找到

**Comment by paderlol** [comment]
可以看一下这个issue #56

**Comment by zw201913** [comment]
可以参考一下这篇博客：https://www.jianshu.com/p/07ad6e817533
