### ISSUE TITLE
When combined with docker service, I found a serious bug.

### ISSUE THREAD

**Issue by nkorange** [nacos-group/nacos-docker#58]
Please see https://github.com/alibaba/nacos/issues/1949

**Comment by lynk-coder** [comment]
halo~

**Comment by lynk-coder** [comment]
I would like to ask why my "nacos-server" runs in the mode of "docker service", which will cause our configuration cannot be updated in real time.
However, after I use "docker run", I can return to normal use.
When I found that the IP monitored by our "nacos-server" was under the "docker service ingress network", nacos entered a state that could not dynamically update the configuration.

**Comment by paderlol** [comment]
I don't konw much about docker service . but I guess the network problem is caused by your ingress

**Comment by sinolbs** [comment]
main :c.a.n.c.i.CredentialWatcher] null No credential found

**Comment by paderlol** [comment]
@lynk-coder 我想如果你在host模式下面是正常的,说明是ip获取问题导致配置中心不正常的,因为在nacos内部会做本地ip的校验,如果你docker内部可能会取到多个地址就会有这个问题,如果你使用的host模式,他应该取的是域名或者主机名,就不会出现这个问题

**Comment by lynk-coder** [comment]
后来我解决了，因为server在docker容器下默认取到的第一张网卡ip是一个无法对外联通的ip




On 01/19/2020 15:33, pader wrote:

@lynk-coder 我想如果你在host模式下面是正常的,说明是ip获取问题导致配置中心不正常的,因为在nacos内部会做本地ip的校验,如果你docker内部可能会取到多个地址就会有这个问题,如果你使用的host模式,他应该取的是域名或者主机名,就不会出现这个问题

**Comment by paderlol** [comment]
@sinolbs  No credential found 这是从哪里报出来的？

**Comment by paderlol** [comment]
@lynk-coder  不好意思回你这么迟,因为最近工作上事情太多了
