### ISSUE TITLE
部署单机版BUG（standalone-derby.yaml）

### ISSUE THREAD

**Issue by yxifu** [nacos-group/nacos-docker#59]
**环境：**
docker --version   1.13.1
**安装过程：**
git clone --depth 1 https://github.com/nacos-group/nacos-docker.git
cd nacos-docker
docker-compose -f example/standalone-derby.yaml up
**异常：**
![image](https://user-images.githubusercontent.com/22695355/68079620-4ff2c280-fe27-11e9-9b47-da522cbae1e3.png)

**Comment by paderlol** [comment]
这不是bug，是你自己docker的权限问题，你的docker应该没有安装正确

**Comment by yxifu** [comment]
> 这不是bug，是你自己docker的权限问题，你的docker应该没有安装正确

- 应该不是docker安装的问题。
- docker已经运行了很多容器了，报过类似的错误，都是影射文件的问题。
- 看配置yml文件，有三个目录影射，另两个都正常。

**Comment by yxifu** [comment]
可能是权限的问题，我再排查排查。
