### ISSUE TITLE
new dockerfile

### ISSUE THREAD

**Issue by zhfish** [nacos-group/nacos-docker#61]
做了一个基于alpine,zulu JDK11,mysql8.0的dockerfile
方便合进来么？

**Comment by paderlol** [comment]
你是直接把jdk升到11做了一个mysql8.0的主从镜像？

**Comment by paderlol** [comment]
如果你是说nacos整个升到11的镜像，暂时不会合并，你可以拿的官方的先改一下，毕竟现在大部分公司都是处于jdk8的版本，甚至更低的版本

**Comment by zealinux** [comment]
@zhfish alpine我们公司特别关心小镜像，这里的CentOS的镜像实在是太大了。希望分享。

@paderlol 希望以后出alpine镜像
