### ISSUE TITLE
[BUG] nacos-server startup faild

### ISSUE THREAD

**Issue by gary0416** [nacos-group/nacos-docker#64]
# startup cmd
```
docker-compose -f example/standalone-mysql.yaml up
```

# version
nacos/nacos-server:latest

# issue
nacos-server startup faild

# log
```
$ cat example/standalone-logsstart.out
nohup: failed to run command '/usr/lib/jvm/java-1.8.0-openjdk/bin/java': No such file or directory
```

nacos/nacos-server:latest files:
![latest](https://user-images.githubusercontent.com/2173239/69316169-351bad00-0c73-11ea-830a-684b8e9b27e4.png)

# reason
#62 

https://github.com/nacos-group/nacos-docker/commit/6e920b16ed514afa8997a04281832d2a05bcb1db

need modify Dockerfile env JAVA_HOME and JAVA

# latest correct version
[nacos/nacos-server:1.1.4](https://hub.docker.com/layers/nacos/nacos-server/1.1.4/images/sha256-9d8d7be3bbadeb96b4796319b8c70e544b86f398a825a8fb2bffb7625dbbc20d)

files:
![1 1 4](https://user-images.githubusercontent.com/2173239/69316147-2634fa80-0c73-11ea-955d-ae1b69489e9d.png)

**Comment by paderlol** [comment]
i got it

**Comment by paderlol** [comment]
Thanks,I'm sorry for that issue

**Comment by fdiskbrain** [comment]
> Thanks,I'm sorry for that issue

I sorry,but i think it does not casue by remove java-1.8.0-openjdk .We can use  jre base image.  I ceate a feature branch.    how about bulid image from alpine stretch. By now ,the image size is so big.

**Comment by paderlol** [comment]
我知道了,应该是你用的quickstart的例子,这个是没用任何卷的,所以会出现不停重新选举,因为选举数据每次都写的是临时文件

**Comment by paderlol** [comment]
We have considered this before, but in order to be unified with the interior, we chose to use a more complete environment.
