### ISSUE TITLE
cluster-ip.yml中的数据挂载问题

### ISSUE THREAD

**Issue by spiralzjt** [nacos-group/nacos-docker#69]
volumes:
      - ./mysql-slave:/var/lib/mysql
这个步骤中挂载的目录mysql-slave是自己创建吗？该目录下需要放什么东西吗？

还有一点，我想要链接RDS数据库，还是通过mysql-master和mysql-slave?此时他们相当于是一个connector的作用？望解答，感谢

**Comment by paderlol** [comment]
你可以通过rds创建主从来进行配置,切换配置中的host就可以了,不过表还需要自己创建
