### ISSUE TITLE
cluster 模式下的主从数据库镜像，是否可以直接应用在生产环境？

### ISSUE THREAD

**Issue by yingzi20** [nacos-group/nacos-docker#70]
cluster 模式下的主从数据库镜像，只是写的一个demo，还是可以放心的应用于生产环境？

**Comment by paderlol** [comment]
Demo 生产需要自己调优一下




| |
浮夸
|
|
邮箱：huangmnlove@163.com
|

签名由 网易邮箱大师 定制

在2020年01月02日 13:21，yingzi2020 写道：

cluster 模式下的主从数据库镜像，只是写的一个demo，还是可以放心的应用于生产环境？
