### ISSUE TITLE
请问nacos单机但mysql在生产环境应该怎么部署呢

### ISSUE THREAD

**Issue by juzi214032** [nacos-group/nacos-docker#73]
我看到有issue里面说项目提供的`standalone-mysql.yml`只是用于测试使用，那我如果想在生产环境使用，单机部署并且只有一个mysql，具体应该怎么操作呢。
如果是使用已经存在的mysql，那么该如何建库建表呢

**Comment by paderlol** [comment]
你可以配置自己的数据库,并且把数据库的数量设置为1就可以了,不用配置两个数据库

**Comment by paderlol** [comment]
MYSQL_DATABASE_NUM 这个环境变量

**Comment by juzi214032** [comment]
> MYSQL_DATABASE_NUM 这个环境变量

`MYSQL_DATABASE_NUM`设置为`1`后就不用配置`MYSQL_SLAVE_SERVICE`这些环境变量了，对吧

**Comment by paderlol** [comment]
恩是的

**Comment by juzi214032** [comment]
建表SQL是[nacos/config/src/main/resources/META-INF/](https://github.com/alibaba/nacos/tree/develop/config/src/main/resources/META-INF)目录下的两个sql文件吗
