### ISSUE TITLE
配置单机MySQL下nacos-mysql-slave:latest下载失败

### ISSUE THREAD

**Issue by Flyerison** [nacos-group/nacos-docker#74]
想在虚拟机上装一个单机Nacos和单MySQL库的小服务：
在standalone-mysql.yaml把相应的MySQL库地址给改掉了，mysql_database_num=1也配好了，两个slave的属性未配置
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=192.168.1.114
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_SLAVE_SERVICE_HOST=
      - MYSQL_SLAVE_SERVICE_PORT=
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=dsadsa2@
      - MYSQL_DATABASE_NUM=1
  但是docker-compose -f example/standalone-mysql.yaml up下拉nacos-mysql-slave:latest镜像一直失败：（centos7下docker配置了阿里等其他的国内镜像地址，docker info下可看到镜像地址配置生效）
Pulling nacos (nacos/nacos-server:latest)...
ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
不知是家里网络不好还是什么其他问题，大佬可以帮忙看下上面的步骤存在问题吗？

**Comment by paderlol** [comment]
网络超时

**Comment by Flyerison** [comment]
。。。。。好吧   可能是家里网络不好
