### ISSUE TITLE
一个容易被误解的小配置

### ISSUE THREAD

**Issue by jenphyjohn** [nacos-group/nacos-docker#75]
文件位置：nacos-docker/example/standalone-mysql.yaml
配置：`- MYSQL_SLAVE_SERVICE_PORT=3305`
联系下边mysql-slave服务的端口映射，这个配置容易被人理解为宿主机的端口：“3305”，实际这里应该配置为容器端口：“3306”，建议修改下，不然容易对人造成误导

**Comment by paderlol** [comment]
谢谢,已经优化了
