### ISSUE TITLE
Nacos使用docker-compose部署，配置mysql主从数据库，主从失效

### ISSUE THREAD

**Issue by jenphyjohn** [nacos-group/nacos-docker#76]
问题和这个nacos主项目中的issue一样
[https://github.com/alibaba/nacos/issues/2362](url)

我是用docker-compose搭建的standalone-mysql版nacos，mysql是主从，db_num数量未配置，看了下配置文件，默认值应该就是2，自从项目跑起来之后测试就开始，从库一直没有同步数据

**Comment by paderlol** [comment]
数据库用的你自己的？

**Comment by paderlol** [comment]
如果你是出现[issue 2362](https://github.com/alibaba/nacos/issues/2362)一样的问题,这个问题是由于程序里面检测到master不可用 然后就切换到slave了,所以造成了这个问题,我在nacos-docker镜像里面做了主从镜像,当时是为了演示这个能力,这个其实生产会出现你这个问题,就是切到从后导致主的数据比从少,出现数据不一致的问题,所以建议改成配一台就好,后续版本会去掉这个配置两个数据库的功能的。

**Comment by jenphyjohn** [comment]
多谢
