### ISSUE TITLE
MYSQL_DATABASE_NUM设置问题

### ISSUE THREAD

**Issue by aaxlong** [nacos-group/nacos-docker#77]
镜像配置默认为 db.num=${MYSQL_DATABASE_NUM:1}
单机和集群使用mysql时，均默认采用主从方式，因此如果不改镜像配置，直接安装使用
nacos就会不断的重启。直接注释掉或者重设置值就可以正常启动。

**Comment by paderlol** [comment]
请注意看wiki，我已经说明了为什么不使用主从数据库，和使用主从的风险
