### ISSUE TITLE
1.2.0 docker集群模式无法正常使用

### ISSUE THREAD

**Issue by yszansx** [nacos-group/nacos-docker#78]
docker源码下载后执行

使用ip 集群模式 报如下错误
![image](https://user-images.githubusercontent.com/43443722/76049785-30b89d00-5fa1-11ea-9f76-d256bd7c7ea4.png)

使用hostname 集群模式 报如下错误
http://192.168.10.55:8848/nacos/#/configurationManagement?dataId=&group=&appName=
![image](https://user-images.githubusercontent.com/43443722/76050209-9dcc3280-5fa1-11ea-865b-d0adc82ed339.png)

**Comment by paderlol** [comment]
已经修复了 重新pull下工程就可以了

**Comment by yszansx** [comment]
![image](https://user-images.githubusercontent.com/43443722/76059353-97e24b80-5fb9-11ea-82ad-6af9abe9c639.png)


![image](https://user-images.githubusercontent.com/43443722/76059254-52258300-5fb9-11ea-8e74-02febcb8aaf4.png)

更新镜像和工程启动后 1.2.0的集群8848  8849  8850三个对外映射端口只有一个能登录web界面吗？

**Comment by paderlol** [comment]
清除下浏览器缓存

**Comment by yszansx** [comment]
可以了 感谢。

**Comment by paderlol** [comment]
不客气,那我关闭掉issue了
