### ISSUE TITLE
*bug report*不能启动权限控制相关功能

### ISSUE THREAD

**Issue by sunny5541** [nacos-group/nacos-docker#79]
## Issue Description

*bug report* 不能启动权限控制的相关功能

### Describe what happened (or what feature you want)

在docker环境变量中添加 TOMCAT_ACCESSLOG_ENABLED=true 和 NACOS_AUTH_ENABLE=true 后权限控制功能没有被启动

### Describe what you expected to happen

打开web页面会跳转到登录界面 或者 在用 API 调用 /nacos/v1/cs/configs 时返回 403。

### How to reproduce it (as minimally and precisely as possible)

1. clone 项目
2. 修改 example/standalone-derby.yaml 文件在 nacos 部分的环境变量中添加 TOMCAT_ACCESSLOG_ENABLED=true  和  NACOS_AUTH_ENABLE=true
3. 启动项目   docker-compose -f example/standalone-derby.yaml up 

### Tell us your environment

OS=Debian GNU/Linux 10 (buster)
docker=19.03.5
docker-compose=1.25.4

### Anything else we need to know?

**Comment by paderlol** [comment]
清楚浏览器缓存先

**Comment by paderlol** [comment]
还有这个TOMCAT_ACCESSLOG_ENABLED 是tomcat 访问日志开关 跟权限没关系 注意看README

**Comment by sunny5541** [comment]
TOMCAT_ACCESSLOG_ENABLED 我理解的有问题，但这个问题应该和浏览器缓存无关。使用API仍然能不认证就获取配置

**Comment by sunny5541** [comment]
sun@jkyyops:~/workspace/nacos-docker$ curl -X GET "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test"
HelloWorldsun@jkyyops:~/workspace/nacos-docker$ 


另外直接下载 alibaba/nacos 单机模式运行不是这个结果。

**Comment by paderlol** [comment]
你用的latest镜像是吧？

**Comment by paderlol** [comment]
还有你打开登陆界面不需要登陆？

**Comment by sunny5541** [comment]
是 latest 镜像  ID是 c9085913dfe1
按上面操作启动的实例是不需要登录就能获取配置的

**Comment by paderlol** [comment]
下载的nacos包配置后启动是可以生效的是吧

**Comment by sunny5541** [comment]
对下载 nacos 包配置后能返回 json
```json
{"timestamp":"2020-03-06T05:55:19.685+0000","status":403,"error":"Forbidden","message":"unknown user!","path":"/nacos/v1/cs/configs"}
```

**Comment by paderlol** [comment]
恩 我找到原因了,我重新发一下镜像,是nacos.security.ignore.urls引发的

**Comment by paderlol** [comment]
好了 重新pull下镜像就可以了
