### ISSUE TITLE
无法创建命名空间

### ISSUE THREAD

**Issue by liyin37** [nacos-group/nacos-docker#80]
使用nacos1.2.0部署到k8s中后，访问nacos的UI去创建命名空间，提示500报错，nacos已经配置好连接到MySQL数据库了，并且MySQL数据库中也有表文件了，这个是什么问题呢
org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL [INSERT INTO tenant_info(kp,tenant_id,tenant_name,tenant_desc,create_source,gmt_create,gmt_modified) VALUES(?,?,?,?,?,?,?)]; Could not retrieve transation read-only status server; nested exception is java.sql.SQLException: Could not retrieve transation read-only status server
![image](https://user-images.githubusercontent.com/42507175/76822711-d34c0800-684c-11ea-866a-a025e40fe609.png)
![image](https://user-images.githubusercontent.com/42507175/76822719-dba44300-684c-11ea-9523-e820e79bf584.png)

**Comment by paderlol** [comment]
这种只有两种情况,
第一你使用了Mysql 8 但是nacos数据库驱动使用的低版本的
第二 你数据库事务隔离级别使用的RP 改成RC
这不是nacos本身的问题,可以自行google或者百度有很多类似的回答
