### ISSUE TITLE
jvm 参数中不需要加上 cgroup 等 参数吗

### ISSUE THREAD

**Issue by WywTed** [nacos-group/nacos-docker#81]
-XX:+UnlockExperimentalVMOptions 
-XX:+UseCGroupMemoryLimitForHeap 
这两个 jvm 参数不用加么； 用来限制不要超过 docker 的 memory 限制

**Comment by paderlol** [comment]
这个参数一直是实验性参数，所以没考虑过进行设置

**Comment by paderlol** [comment]
如果你想配置这个，可以通过JAVA_OPT这个变量进行设置
