### ISSUE TITLE
1.2.0部署的nacos docker数据库 nacos角色有问题

### ISSUE THREAD

**Issue by ordercard** [nacos-group/nacos-docker#82]
![image](https://user-images.githubusercontent.com/22793054/77517602-602f3b00-6eb7-11ea-9ab2-20117db11e2e.png)
正确的是ROLE_ADMINI   错误的是GLOBAL_ADMIN，否则会调用好多接口403 、并且权限控制菜单不可见

让我纠结半天

**Comment by paderlol** [comment]
1.2.0？

**Comment by paderlol** [comment]
我晚点比对下吧

**Comment by ordercard** [comment]
嗯是的，我已经对比过了，而且我发现 现在的springboot-cloud-nacos用的居然是1.1.4的nacos-client客户端，有权限的客户端代码版本是1.2.0，这个需要springboot-cloud-nacos 如果要用权限管理需要改代码
![image](https://user-images.githubusercontent.com/22793054/77532894-c1173d00-6ed0-11ea-9c50-4591228cfb49.png)
zhe'y这一块的

**Comment by paderlol** [comment]
我先确认下这个角色是不是确实要用这个，然后cloud的问题，你可以选择自己强行覆盖客户端版本，如果不行就提issue给cloud那边吧

**Comment by paderlol** [comment]
那个角色的已经修复了

**Comment by paderlol** [comment]
重新拉下mysql镜像就好了
