### ISSUE TITLE
docker-compose构建nacos一直报错

### ISSUE THREAD

**Issue by wxywizard** [nacos-group/nacos-docker#86]
[root@vdaps3 nacos-docker]# docker-compose -f example/standalone-derby.yaml up
Pulling nacos (nacos/nacos-server:latest)...
latest: Pulling from nacos/nacos-server
5ad559c5ae16: Pulling fs layer
152a60b4a0e4: Pulling fs layer
f2b467c6c505: Pulling fs layer
f82f0a6a31a9: Waiting
9e3844de6ce4: Waiting
6d64a4f62bac: Waiting
3da7ef5287a5: Waiting
886be0ec2785: Waiting
ERROR: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/94/?verify=1585738005-oBM%2FohMveoJNlPHawvAuHw2Uu1M%3D: dial tcp 104.18.124.25:443: i/o timeout

**Comment by paderlol** [comment]
你pull  镜像超时啊，这是你自己的网络的问题

**Comment by wxywizard** [comment]
> 你pull 镜像超时啊，这是你自己的网络的问题

你好，这个问题我弄好了，我用官网给的docker-compose方式安装nacos docker，版本还是1.2.0，是不是还没更新1.2.1呢？
我之后把分支切换到1.2.1 用build文件夹的Dockerfile重新build镜像，之后无法启动。具体是在build文件夹执行命令docker build -t [仓库名]:[tag]. 之后再docker images 我看到生成了none的镜像200M左右，但是我之前把本地镜像nacos都删除过了，不应该出现none，并且我重新换了仓库名build之后还是出现none的镜像。
能否请教下，这个自己build镜像的时候应该怎么做呢？因为1.2.0配置文件版本回退有问题，生产环境急需要更新1.2.1麻烦了。

**Comment by paderlol** [comment]
现在1.2.1的tag已经发布了的，你可以指定1.2.1的tag，我明天会把latest更新到1.2.1

**Comment by wxywizard** [comment]
> 现在1.2.1的tag已经发布了的，你可以指定1.2.1的tag，我明天会把latest更新到1.2.1

你好，我想问下我用docker-compose -f example/standalone-mysql-5.7.yaml up启动nacos的时候报错没有找到表，Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'nacos.config_info' doesn't exist
这个表不会初始化吗？

**Comment by paderlol** [comment]
如果你用自己的数据库，就得你自己初始化

**Comment by wxywizard** [comment]
> 如果你用自己的数据库，就得你自己初始化

我用的是nacos/nacos-mysql:5.7 镜像 就是example/standalone-mysql-5.7.yaml里面配置的

**Comment by paderlol** [comment]
那数据库会自动初始化

**Comment by wxywizard** [comment]
> 那数据库会自动初始化

但是他没有初始化。。。是哪的配置有问题吗？ 我连接那个mysql看到nacos库是空的？

**Comment by paderlol** [comment]
我看下

**Comment by wxywizard** [comment]
> 我看下

我的配置如下
mysql.env
MYSQL_ROOT_PASSWORD=Sailing@123
MYSQL_DATABASE=nacos
MYSQL_USER=root
MYSQL_PASSWORD=Sailing@123
---------------------------------------------------
nacos-standlone-mysql.env

PREFER_HOST_MODE=hostname
MODE=standalone
NACOS_AUTH_ENABLE=true
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=172.20.32.53
MYSQL_SERVICE_DB_NAME=nacos
MYSQL_SERVICE_PORT=3308
MYSQL_SERVICE_USER=root
MYSQL_SERVICE_PASSWORD=Sailing@123

**Comment by paderlol** [comment]
我这边试了 没有这个问题,还有你为什么要自己配置一个host

**Comment by wxywizard** [comment]
> 我这边试了 没有这个问题,还有你为什么要自己配置一个
这个不用配置mysql连接吗？

**Comment by paderlol** [comment]
我配置的mysql就是连接

**Comment by paderlol** [comment]
然后你可以自己确认下/example/mysql目录下面有没有那几张表存在,如果没有删除掉mysql目录,删除container然后进行连接

**Comment by wxywizard** [comment]
> 然后你可以自己确认下/example/mysql目录下面有没有那几张表存在,如果没有删除掉mysql目录,删除container然后进行连接
我删掉mysql目录重新弄，就创建失败了。。
Version: '5.7.26'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
mysql         | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql         | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql         | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql         | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql         | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql         | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql         | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'

**Comment by paderlol** [comment]
还有mysql_user不要指定root,root是root mysql_user 是user

**Comment by paderlol** [comment]
对mysql的使用建议参考下Mysql的官方镜像配置

**Comment by wxywizard** [comment]
> 对mysql的使用建议参考下Mysql的官方镜像配置

好的，谢谢 mysql弄好了 是因为用户的原因，现在表也创建了，但是nacos还是起动报错，连不上数据库，但是我用navicat可以连接。
配置如下
nacos-standlone-mysql.env

PREFER_HOST_MODE=ip
MODE=standalone
NACOS_AUTH_ENABLE=true
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=mysql
MYSQL_SERVICE_DB_NAME=nacos_dev
MYSQL_SERVICE_PORT=3308
MYSQL_SERVICE_USER=nacos
MYSQL_SERVICE_PASSWORD=nacos


----------------------------------------
mysql.env

MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=nacos_dev
MYSQL_USER=nacos
MYSQL_PASSWORD=nacos





报错信息：
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2085)
	... 194 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	... 196 more

**Comment by paderlol** [comment]
3308是什么端口?

**Comment by wxywizard** [comment]
> 对mysql的使用建议参考下Mysql的官方镜像配置
弄好了，谢谢你。
但是这个配置还是要改成ip用mysql一直连不上，不知道为啥？
MYSQL_SERVICE_HOST=mysql

**Comment by wxywizard** [comment]
> 3308是什么端口?

宿主机端口

**Comment by paderlol** [comment]
重启一次就好了,因为第一次启动的时候数据库并没有初始化完全启动成功nacos就已经启动了,所以重启下就好了

**Comment by wxywizard** [comment]
我试了一下对于这个配置MYSQL_SERVICE_HOST要是具体ip那么MYSQL_SERVICE_PORT要用宿主机端口。要是container_name就用3306这个端口，但是我用ip的话好像不用重启的。。

建议，能否把这些配置文件弄个文档描述下，小白看的不太明白。

**Comment by paderlol** [comment]
有配置文档，在readme里面啊，你如果双方在一个docker里面，无需用宿主机ip和端口啊，你如果是宿主机当然需要配置，这个是docker本身的特性

**Comment by wxywizard** [comment]
> 有配置文档，在readme里面啊，你如果双方在一个docker里面，无需用宿主机ip和端口啊，你如果是宿主机当然需要配置，这个是docker本身的特性

好的，谢谢你帮我排查问题。麻烦了

**Comment by paderlol** [comment]
客气
