### ISSUE TITLE
nacos surport mysql in the case of stand-alone mode 

### ISSUE THREAD

**Issue by gumutianqi** [nacos-group/nacos-docker#9]
0.7.0 版本 stand-alone 已经支持 mysql, docker 需要跟进
https://github.com/alibaba/nacos/issues/395

**Comment by paderlol** [comment]
好的,我晚上更新下, 如果你目前需要体验的话可以把conf/application.properties 映射到宿主机配置spring.datasource.platform使用
```Java
#other config ..
spring.datasource.platform=mysql
```
配置后请注意配置Mysql数据库

> 0.7.0 版本 stand-alone 已经支持 mysql, docker 需要跟进
> [alibaba/nacos#395](https://github.com/alibaba/nacos/issues/395)
