### ISSUE TITLE
关于nacos各个服务启动的问题？

### ISSUE THREAD

**Issue by yuanjinzhong** [nacos-group/nacos-docker#90]
你好,我这俩天刚开始学习nacos,然后我发现了这个仓库，我docker-compose启动后，发现nacos-console控制台可以正常访问，服务也可以正常注册到nacos。这是一键启动？我以为最起码会启动三个服务:控制台，注册中心，配置中心。
但是我打开docker-startup.sh发现zhi只启动了一个jar包
![image](https://user-images.githubusercontent.com/13908993/80556869-9eb09c00-8a07-11ea-91f0-d5ed33b2b0fb.png)
请问nacos是服务是如何做到启动一个服务，提供多种服务的

**Comment by paderlol** [comment]
因为服务都在jar包里面，具体可以参考下官网的文档

**Comment by yuanjinzhong** [comment]
好吧我以为会像rocketmq一样，nameserver 是nameserver,broke是broke 挨个启动呢

**Comment by yuanjinzhong** [comment]
你好，还有一个问题，服务注册用到的表是哪一个？我在数据库里面没找到
