### ISSUE TITLE
docker-compose -f example/standalone-mysql.yaml up   执行不了 ，提示没找到该文件

### ISSUE THREAD

**Issue by LYDXY** [nacos-group/nacos-docker#91]
docker-compose -f example/standalone-mysql.yaml up   执行不了，  换成  

docker-compose -f example/standalone-mysql-5.7.yaml up  也只想不了，提示 缺少 环境

**Comment by zw201913** [comment]
建议自己搭建数据库环境，可以参考一下这篇博客：https://www.jianshu.com/p/07ad6e817533
