### ISSUE TITLE
在哪儿能正确设置日志级别

### ISSUE THREAD

**Issue by ordercard** [nacos-group/nacos-docker#94]
怎么设置日志级别？ 我现在一天光日志就打印2个g，找半天没也看到那儿能关闭服务的日志

**Comment by paderlol** [comment]
关闭项目日志还是tomcat 请求日志？

**Comment by paderlol** [comment]
如果是项目日志可以自己挂一个custom.properties去操作，或者直接挂一个logback.xml

**Comment by ordercard** [comment]
![image](https://user-images.githubusercontent.com/22793054/82184932-02e5c200-991b-11ea-9c86-70e0c3a08e8b.png)
我整准备挂个nacos-logback.xml...，另外  custom.properties有模板吗，我没找到

**Comment by paderlol** [comment]
custom.properties 其实相当于application.properties，不过配置的属性优先级高于application.properties

**Comment by paderlol** [comment]
挂在conf下面就可以了，在docker例子里面有的
