### ISSUE TITLE
除了mysql，还支持其他数据库嘛？

### ISSUE THREAD

**Issue by zw201913** [nacos-group/nacos-docker#98]
除了mysql，还支持其他数据库嘛？

**Comment by yuanyunchu** [comment]
有自带的

**Comment by siblesos** [comment]
docker run --name nacos -d -p 8048:8848 --privileged=true --restart=always -e JVM_XMS=512m -e JVM_XMX=1048m -e MODE=standalone -e PREFER_HOST_MODE=ip -v /data/docker/nacos/logs:/home/nacos/logs  nacos/nacos-server:1.1.3
这么启动的，如何找回忘记的密码呢？我修改了初始密码，但是忘记了。

**Comment by paderlol** [comment]
暂时不支持，这种密码忘记了你只能自己改库了

**Comment by siblesos** [comment]
> 暂时不支持，这种密码忘记了你只能自己改库了

我在容器没找的数据库，默认是mysql吗？

**Comment by paderlol** [comment]
默认是嵌入式，这种不适合生产用

**Comment by siblesos** [comment]
> 默认是嵌入式，这种不适合生产用

好的，谢谢您！祝安！
